### ISSUE TITLE
listen EACCES: permission denied 0.0.0.0:4001 (Win10)

### ISSUE THREAD

**Issue by Makeshift** [Budibase/budibase#1037]
### Error that occurred when using the budibase builder:
```
Error: listen EACCES: permission denied 0.0.0.0:4001
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Object.<anonymous> (C:\Users\Connor\AppData\Local\Programs\Budibase Builder\resources\app.asar\src\app.js:53:25)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at createWindow (C:\Users\Connor\AppData\Local\Programs\Budibase Builder\resources\app.asar\src\electron.js:48:18)
```
### Operating System Information:
---

Budibase Builder 0.6.2
Electron 10.1.3
win32 10.0.19042
Locale: en-GB

### Info
---
First time starting and trying to use Budibase on Win10. I see that #824 was raised in order to fix these a similar (but not identical!) issue with port 4001 on linux. This however appears to be an issue with node binding to a lot of ports in Windows. Note this isn't a `EADDRINUSE`, it's `EACCES`, and is not solved by using an elevated shell.

A quick test with a horrid script I threw together:

```node
const start = 1000;
const max = 10000;

function testPort(port) {
    const server = require('http').createServer();
    server.on('error', (e) => {
        console.log(`${port}: FAIL`);
        server.close(() => {
            if (port < max) testPort(++port);
        })
    })
    server.listen(port, () => {
        console.log(`${port}: SUCCESS`)
        server.close(() => {
            if (port < max) testPort(++port);
        })
    });
}

testPort(start)
```

Shows that Windows seems to block random groups of ports for no apparent reason? eg.
1000-1142: Success
1143-1342: Fail
1343-1564: Success
1565-1664: Fail
...
3515-4014: Fail (4001 being in this range :( )
etc.
(They're all `EACCES`)

It's likely this is an issue that should be raised with node rather than you guys, but I'm curious if a simple function that iterates through a few ports to check if it can bind to any would solve this for now.

**Comment by mike12345567** [comment]
@Makeshift This is some fantastic debugging! I'll have to check this out and see what would be the best option, by the look of things we should consider simply moving ports - its possible Windows reserves a few groups of ports for ephemeral purposes! This does look like a discussion for the Node guys though, very odd what's going on with it there!

I'll have a bit of a deeper dive myself and see if raising the port number to something in a 10,000-20,000 range would solve the issue.

**Comment by shogunpurple** [comment]
Should be resolved with dynamic port allocation in https://github.com/Budibase/budibase/pull/1083. Closing
