### ISSUE TITLE
yarn add Or npm install  Error

### ISSUE THREAD

**Issue by OPEN-9** [Budibase/budibase#10502]
Unexpected error -  TypeError: Cannot read properties of undefined (reading 'command')
    at Command.configure (/snapshot/budibase/packages/cli/dist/structures/Command.js:39:31)
    at /snapshot/budibase/packages/cli/dist/index.js:29:21
    at Generator.next (<anonymous>)
    at /snapshot/budibase/packages/cli/dist/index.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/snapshot/budibase/packages/cli/dist/index.js:5:12)
    at init (/snapshot/budibase/packages/cli/dist/index.js:22:12)
    at Object.<anonymous> (/snapshot/budibase/packages/cli/dist/index.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (pkg/prelude/bootstrap.js:1937:32)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47

![image](https://user-images.githubusercontent.com/42791280/236614059-5b32175b-bd76-402a-a780-42d0744e0fbf.png)

**Comment by OPEN-9** [comment]
In this case, how can I solve it?

**Comment by cloudbring** [comment]
I am seeing a similar issue:

Tried with node `v16.13.2` (Demo version from https://vimeo.com/showcase/budibase-get-started) and `v18.16.0` (Latest LTS at the time of writing). Both fresh installs. Both using a global budi (`npm install -g @budibase/cli`)

```bash
$ budi
> Error - Failed to run CLI command - please report with the following message:
> Error - Error: Cannot find a valid version in its package.json
```

**Comment by cmuc24** [comment]
on Ubuntu 22.04.2 LTS
- same with node installed native (nodesource), also via nvm
- via root, and also via sudo user

without sudo, faialed with permission error (only with native installed node)

```bash
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/lib/node_modules/@budibase
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@budibase'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@budibase'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/lib/node_modules/@budibase'
npm ERR! }
```
