### ISSUE TITLE
[BUDI-7001] MySQL TIME type column breaks time-only date picker in forms and grid, crashes builder

### ISSUE THREAD

**Issue by andz-bb** [Budibase/budibase#10609]
**Checklist**

* [X] I have searched budibase discussions and GitHub issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.6.11
  * App Version: 2.6.11

**Describe the bug**
When trying to load a screen with a time-only date picker present, the app preview freezes and the following error appears in the console:

```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'tabIndex')
    at buildMonthSwitch (index.js?v=19f05e52:580:47)
    at jumpToDate (index.js?v=19f05e52:341:13)
    at Object.setDate (index.js?v=19f05e52:1684:9)
    at $$self.$$.update (Flatpickr.svelte:29:7)
    at update (index.mjs:1294:12)
    at flush (index.mjs:1258:17)
```

![image.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/5bdabaae-afad-48c0-9166-1aa2127139b1/7adecdec-1e7c-4b15-b675-0c6ee2ce5136)

The same issue occurs with the grid view in the data section when trying to work with these MySQL Time type columns.

![image.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/262fa1de-3df4-4a9a-bddb-2c812f4e637b/3763e806-6427-433b-a468-57e281fede49)

This is a significant issue as in both cases the app preview or builder freezes following the error.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a MySQL table with a TIME type column
2. Add the MySQL DB as a datasource with the new table
3. Go to the grid view and try to add a record with a value for time
4. The builder will freeze when trying to interact with the time picker. Invalid date is shown.
5. (the time picker control has the same issue in design view)
6. Create a form with a Date picker field linked to the time column
7. Make sure the Date picker is set to Time only
8. Try to load the component or interact with it - the screen freezes with the same error

**Expected behaviour**
Date/time picker component should load for this data type and be usable.

**Additional Context**

[Raised by community member here](https://github.com/Budibase/budibase/discussions/10566)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7001](https://linear.app/budibase/issue/BUDI-7001/mysql-time-type-column-breaks-time-only-date-picker-in-forms-and-grid)</sub>

**Comment by aptkingston** [comment]
Initial investigation points to an actual issue with flatpickr. We are properly setting the `noCalendar` option when time-only fields are used, but flatpickr is attempting to reference calendar DOM component which do not exist on time-only fields. I'll see if we can work around it but this one isn't caused by us.

**Comment by udsonassis** [comment]
@aptkingston @andz-bb 
How could I solve this problem without using flatpickr? Do you have another alternative? At the moment my application is stopped for this reason. In previous version of Budibase this works. This stopped working after I updated the BB version. I don't remember which version I had before.

**Comment by aptkingston** [comment]
Hey @udsonassis. You can't remove flatpickr at the moment - it's the library we're using behind the scenes for our date picker component and it's not possible to change that. You could technically write a component plugin for your own date picker, and use that inside your apps, but if you're using the data section inside Budibase you have to use our date picker.
If we can't somehow work around this issue then we might be forced to move away from flatpickr very soon though, so either way we will have this working again before too long.

**Comment by udsonassis** [comment]
@aptkingston Do you have an estimate of when this fix will be released? 
What do I need to do to upgrade my self-hosted instance?

**Comment by udsonassis** [comment]
@aptkingston I saw that version 2.6.16 was released, I updated it, but the problem remains.

**Comment by aptkingston** [comment]
@udsonassis apologies for not being clearer, but I meant our next monthly release. So in this case, our May release which will go out at the start of June.

**Comment by udsonassis** [comment]
@aptkingston Thank you for your support and attention. Got it, unfortunately I'm going to have to drop budibase, I can't wait that long with my app stop, it has multiple pages that use the time picker.
