### ISSUE TITLE
Dev environment: Cannot find module '@budibase/types' 

### ISSUE THREAD

**Issue by jolice** [Budibase/budibase#11068]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

https://github.com/Budibase/budibase/discussions/10415 didn't help me, still get the same error.

**Hosting**

Deploying dev environment on Linux.

```[root@597169 budibase]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
```

**Describe the bug**

Dev environment won't start:

```
@budibase/shared-core: [1] 
@budibase/shared-core: [0] src/filters.ts(1,64): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] src/helpers/helpers.ts(1,22): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] src/helpers/integrations.ts(1,40): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] 
@budibase/shared-core: [0] 1:08:19 PM - Found 3 errors. Watching for file changes.
@budibase/shared-core: [1] src/filters.ts(1,64): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] src/helpers/helpers.ts(1,22): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] src/helpers/integrations.ts(1,40): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] 
@budibase/shared-core: [1] 1:08:19 PM - Found 3 errors. Watching for file changes.
```

**To Reproduce**

```
npm install -g yarn lerna jest
git clone https://github.com/Budibase/budibase.git && cd budibase
cd budibase
yarn dev
```

**Expected behavior**

Dev environment is deployed normally.

**Comment by jolice** [comment]
**upd**: I've figured out that an issue is caused by missing Python 3.0 and `make`. I've installed both packages, ran `yarn build` and now get the error:

```       
failed to load config from /opt/bb-dev/budibase/packages/builder/vite.config.js
       error during build:
       Error: Cannot find module '@sveltejs/vite-plugin-svelte'
       Require stack:
       - /opt/bb-dev/budibase/packages/builder/vite.config.js
       - /root/.nvm/versions/node/v14.21.3/lib/node_modules/vite/dist/node/chunks/dep-e8f070e8.js
           at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
           at Function.Module._load (internal/modules/cjs/loader.js:774:27)
           at Module.require (internal/modules/cjs/loader.js:1003:19)
           at require (internal/modules/cjs/helpers.js:107:18)
           at Object.<anonymous> (/opt/bb-dev/budibase/packages/builder/vite.config.js:36:33)
           at Module._compile (internal/modules/cjs/loader.js:1114:14)
           at Object._require.extensions.<computed> [as .js] (file:///root/.nvm/versions/node/v14.21.3/lib/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64524:24)
           at Module.load (internal/modules/cjs/loader.js:979:32)
           at Function.Module._load (internal/modules/cjs/loader.js:819:12)
           at Module.require (internal/modules/cjs/loader.js:1003:19)
```

**Comment by jolice** [comment]
I will reinstall OS and try everything from scratch.

**Comment by jolice** [comment]
Hi @mike12345567 ,

I've reinstalled Debian 11, executed all commands with accordance to Debian environment setup instruction (https://github.com/Budibase/budibase/blob/0d429daac4263f9c816812f0499c7ad22b14110b/docs/DEV-SETUP-DEBIAN.md), and ran the following commands:

```
yarn setup
yarn dev
```

```
Still, I get the same error:


@budibase/types: [1] 
@budibase/shared-core: [0] src/filters.ts(1,64): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] src/helpers/helpers.ts(1,22): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] src/helpers/integrations.ts(1,40): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] src/filters.ts(1,64): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] src/helpers/helpers.ts(1,22): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] src/helpers/integrations.ts(1,40): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] 
@budibase/shared-core: [1] 3:21:25 PM - Found 3 errors. Watching for file changes.
@budibase/shared-core: [0] 
@budibase/shared-core: [0] 3:21:25 PM - Found 3 errors. Watching for file changes.
@budibase/types: [0] 
@budibase/types: [0] 3:21:34 PM - Found 0 errors. Watching for file changes.
@budibase/types: [1] 
@budibase/types: [1] 3:21:35 PM - Found 0 errors. Watching for file changes.
3:22:12 PM - Starting compilation in watch mode...
@budibase/types: [0] 
@budibase/types: [1] 3:22:12 PM - Starting compilation in watch mode...
@budibase/types: [1] 
@budibase/shared-core: [1] src/filters.ts(1,64): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] src/helpers/helpers.ts(1,22): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] src/helpers/integrations.ts(1,40): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] 
@budibase/shared-core: [1] 3:22:21 PM - Found 3 errors. Watching for file changes.
@budibase/shared-core: [0] src/filters.ts(1,64): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] src/helpers/helpers.ts(1,22): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] src/helpers/integrations.ts(1,40): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] 
@budibase/shared-core: [0] 3:22:22 PM - Found 3 errors. Watching for file changes.
@budibase/types: [1] 
@budibase/types: [1] 3:22:29 PM - Found 0 errors. Watching for file changes.
@budibase/types: [0] 
@budibase/types: [0] 3:22:30 PM - Found 0 errors. Watching for file changes.
@budibase/string-templates: rollup v2.79.1
@budibase/string-templates: bundles src/index.mjs → dist/bundle.mjs...
```

**Comment by jolice** [comment]
If it's important, I also get the following error:

```
warning Resolution field "@budibase/backend-core@0.0.0" is incompatible with requested version "@budibase/backend-core@2.7.36-alpha.9"
warning Resolution field "@budibase/shared-core@0.0.0" is incompatible with requested version "@budibase/shared-core@2.7.36-alpha.9"
warning Resolution field "@budibase/string-templates@0.0.0" is incompatible with requested version "@budibase/string-templates@2.7.36-alpha.9"
warning Resolution field "@budibase/types@0.0.0" is incompatible with requested version "@budibase/types@2.7.36-alpha.9"
warning Resolution field "@budibase/backend-core@0.0.0" is incompatible with requested version "@budibase/backend-core@2.7.36-alpha.9"
warning Resolution field "@budibase/shared-core@0.0.0" is incompatible with requested version "@budibase/shared-core@2.7.36-alpha.9"
warning Resolution field "@budibase/string-templates@0.0.0" is incompatible with requested version "@budibase/string-templates@2.7.36-alpha.9"
warning Resolution field "@budibase/types@0.0.0" is incompatible with requested version "@budibase/types@2.7.36-alpha.9"
```

**Comment by mike12345567** [comment]
Hi @jolice - what docker processes do you have running behind this? Is there a `budibase/proxy` container running correctly?

**Comment by jolice** [comment]
@mike12345567 hi,

No docker processes are running in the background:

```
root@597169:~# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

Now, after running yarn build I get the following:

```
root@597169:~/budibase# yarn build
yarn run v1.22.19
$ yarn nx run-many -t=build
$ /root/budibase/node_modules/.bin/nx run-many -t=build

    ✔  nx run @budibase/server:build (12s)
    ✔  nx run @budibase/worker:build (6s)

    ✖  nx run @budibase/string-templates:build
$ tsc && rollup -c
       /bin/sh: 1: rollup: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       
    ✔  nx run @budibase/types:build (29s)
    ✔  nx run @budibase/shared-core:build (15s)

    ✖  nx run @budibase/backend-core:build
$ rimraf dist/
$ tsc -p tsconfig.build.json
       jest.config.ts(4,26): error TS2694: Namespace '"/root/budibase/node_modules/@jest/types/build/Config"' has no exported member 'InitialProjectOptions'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 10 projects (1m)
 
    ✔    4/6 succeeded [0 read from cache]
 
    ✖    2/6 targets failed, including the following:
         - nx run @budibase/string-templates:build
         - nx run @budibase/backend-core:build
 
   Hint: Try "nx view-logs" to get structured, searchable errors logs in your browser.
 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@597169:~/budibase# 
```

**Comment by mike12345567** [comment]
Hi @jolice - you'll need to run a top level `yarn` by the look of things to install all required dependencies - the steps for getting setup to contribute are here: https://github.com/Budibase/budibase/blob/develop/docs/CONTRIBUTING.md

**Comment by jolice** [comment]
Thanks @mike12345567, let me do it and write back.

**Comment by jolice** [comment]
Hi @mike12345567, I've followed all the steps listed in the instruction (https://github.com/Budibase/budibase/blob/develop/docs/CONTRIBUTING.md), but the error persists.

I've ran top-level `yarn`, then `yarn-setup`, and a still get the error.

```
root@597169:~/budibase# yarn setup
yarn run v1.22.19
$ git config submodule.recurse true && git submodule update && node ./hosting/scripts/setup.js && yarn && yarn build && yarn dev
Docker installed - continuing.
$ node scripts/syncProPackage.js
[1/4] Resolving packages...
warning Resolution field "@budibase/backend-core@0.0.0" is incompatible with requested version "@budibase/backend-core@2.7.36-alpha.9"
warning Resolution field "@budibase/shared-core@0.0.0" is incompatible with requested version "@budibase/shared-core@2.7.36-alpha.9"
warning Resolution field "@budibase/string-templates@0.0.0" is incompatible with requested version "@budibase/string-templates@2.7.36-alpha.9"
warning Resolution field "@budibase/types@0.0.0" is incompatible with requested version "@budibase/types@2.7.36-alpha.9"
warning Resolution field "@budibase/backend-core@0.0.0" is incompatible with requested version "@budibase/backend-core@2.7.36-alpha.9"
warning Resolution field "@budibase/shared-core@0.0.0" is incompatible with requested version "@budibase/shared-core@2.7.36-alpha.9"
warning Resolution field "@budibase/string-templates@0.0.0" is incompatible with requested version "@budibase/string-templates@2.7.36-alpha.9"
warning Resolution field "@budibase/types@0.0.0" is incompatible with requested version "@budibase/types@2.7.36-alpha.9"
success Already up-to-date.
$ husky install
husky - Git hooks installed
$ yarn nx run-many -t=build
$ /root/budibase/node_modules/.bin/nx run-many -t=build

    ✔  nx run @budibase/string-templates:build  [local cache]
    ✔  nx run @budibase/types:build  [local cache]
    ✔  nx run @budibase/bbui:build  [local cache]
    ✔  nx run @budibase/shared-core:build  [local cache]
    ✔  nx run @budibase/server:build  [local cache]
    ✔  nx run @budibase/client:build  [local cache]
    ✔  nx run @budibase/worker:build  [local cache]
    ✔  nx run @budibase/backend-core:build  [local cache]
    ✔  nx run @budibase/builder:build  [local cache]
    ✔  nx run @budibase/cli:build  [local cache]

4:20:32 PM - Starting compilation in watch mode...
@budibase/types: [0] 
@budibase/types: [1] 4:20:32 PM - Starting compilation in watch mode...
@budibase/types: [1] 
@budibase/shared-core: [0] src/filters.ts(1,64): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] src/helpers/helpers.ts(1,22): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] src/helpers/integrations.ts(1,40): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] 
@budibase/shared-core: [0] 4:20:40 PM - Found 3 errors. Watching for file changes.
@budibase/shared-core: [1] src/filters.ts(1,64): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] src/helpers/helpers.ts(1,22): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] src/helpers/integrations.ts(1,40): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] 
@budibase/shared-core: [1] 4:20:41 PM - Found 3 errors. Watching for file changes.
```

**Comment by jolice** [comment]
Hi @mike12345567, I've the following images:

```
root@597169:~# docker image ls
REPOSITORY                                 TAG       IMAGE ID       CREATED         SIZE
minio/minio                                latest    4de87d6c6dd6   7 hours ago     262MB
budibase/proxy                             latest    1643ef0d3e9f   6 days ago      187MB
budibase.docker.scarf.sh/budibase/apps     latest    f91fd5f285f4   6 days ago      3.06GB
budibase.docker.scarf.sh/budibase/worker   latest    22d76df61aad   6 days ago      1.59GB
redis                                      latest    8e69fcb59ff4   2 weeks ago     130MB
curlimages/curl                            latest    4c2629951caa   2 weeks ago     22.7MB
containrrr/watchtower                      latest    f847e1adb570   5 months ago    14.6MB
ibmcom/couchdb3                            latest    b53d45e6ef2b   16 months ago   563MB
```

After running yarn dev, I see the following output:

```
5:00:11 PM - Starting compilation in watch mode...
@budibase/types: [0] 
@budibase/types: [1] 5:00:11 PM - Starting compilation in watch mode...
@budibase/types: [1] 
@budibase/shared-core: [0] src/filters.ts(1,64): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] src/helpers/helpers.ts(1,22): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] src/helpers/integrations.ts(1,40): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [0] 
@budibase/shared-core: [0] 5:00:21 PM - Found 3 errors. Watching for file changes.
@budibase/shared-core: [1] src/filters.ts(1,64): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] src/helpers/helpers.ts(1,22): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] src/helpers/integrations.ts(1,40): error TS2307: Cannot find module '@budibase/types' or its corresponding type declarations.
@budibase/shared-core: [1] 
@budibase/shared-core: [1] 5:00:21 PM - Found 3 errors. Watching for file changes.
@budibase/types: [1] 
@budibase/types: [1] 5:00:31 PM - Found 0 errors. Watching for file changes.
@budibase/types: [0] 
@budibase/types: [0] 5:00:31 PM - Found 0 errors. Watching for file changes.
@budibase/string-templates: rollup v2.79.1
@budibase/string-templates: bundles src/index.mjs → dist/bundle.mjs...
@budibase/string-templates: created dist/bundle.mjs in 19.2s
@budibase/client: created dist/budibase-client.js in 1m 40.1s
```

And that's it.

Should I wait more or something is more?

**Comment by mike12345567** [comment]
@jolice - are you running an up to date version of off of `develop`? Also you should not have the app and worker services running - that looks like you're running a self hosted docker-compose version of Budibase on the same system you're trying to run the development stack - this is likely to have a port clash. The command `yarn dev` should start the docker containers needed if you are up to date and everything is working correctly.
