### ISSUE TITLE
listen EADDRINUSE: address already in use :::4001

### ISSUE THREAD

**Issue by boereman** [Budibase/budibase#1186]
### Error that occurred when using the budibase builder:
```
Error: listen EADDRINUSE: address already in use :::4001
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Object.<anonymous> (C:\Users\taylo\AppData\Local\Programs\Budibase Builder\resources\app.asar\src\app.js:53:25)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at createWindow (C:\Users\taylo\AppData\Local\Programs\Budibase Builder\resources\app.asar\src\electron.js:48:18)
```
### Operating System Information:
---

Budibase Builder 0.7.8
Electron 10.1.3
win32 10.0.21318
Locale: en-US

**Comment by shogunpurple** [comment]
@boereman this one will be resolved with tomorrows release - the builder will start up on an unallocated port on your machine, solving this problem 👍 

You can work around it for now by stopping the process you currently have running on port 4001.
