### ISSUE TITLE
cli tool: Error: ENOTDIR: not a directory, mkdir './buddi/prebuilds/linux-x64'

### ISSUE THREAD

**Issue by kivi** [Budibase/budibase#11947]
**Checklist**
- [x ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: cli-linux 2.11.0

**Describe the bug**
I have downloaded buddi-cli and on execution I see following error:

```sh
./buddi 
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOTDIR: not a directory, mkdir '.../buddibase/buddi/prebuilds/linux-x64'
    at Object.mkdirSync (node:fs:1394:3)
    at Object.mkdirSync (pkg/prelude/bootstrap.js:1642:33)
    at checkForBinaries (/snapshot/budibase/packages/cli/dist/index.js:724733:24)
    at Object.<anonymous> (/snapshot/budibase/packages/cli/dist/index.js:724723:3)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._compile (pkg/prelude/bootstrap.js:1937:32)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12) {
  errno: -20,
  syscall: 'mkdir',
  code: 'ENOTDIR',
  path: '.../buddibase/buddi/prebuilds/linux-x64'
}

Node.js v18.5.0
```

**To Reproduce**
1. Download cli: wget https://github.com/Budibase/budibase/releases/latest/download/cli-linux   
2. Rename: mv ./cli-linux buddi
3. Make executable: chmod +x ./buddi
4. Execute: .`/buddi` or `,/buddi hosting --init`

**Expected behavior**
Should work as described in docs: https://docs.budibase.com/docs/budibase-cli-setup#backing-up-data-using-the-budibase-cli

**Command Line:**
 - OS: Linux/Ubuntu

Workaround:
`npm install @budibase/cli`
`npx buddi`

This seems to work. 

_Side info: I installed the cli to create a working .env file for docker-compose. Unfortunatly that's a different story. The .env is not working with couchdb credentials... needs to be modified_

**Comment by mike12345567** [comment]
This should be resolved as of release 2.11.6.
