### ISSUE TITLE
listen EACCES: permission denied 0.0.0.0:4001

### ISSUE THREAD

**Issue by marens101** [Budibase/budibase#1218]
### Error that occurred when using the budibase builder:
```
Error: listen EACCES: permission denied 0.0.0.0:4001
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Object.<anonymous> (C:\Users\maren\AppData\Local\Programs\Budibase Builder\resources\app.asar\src\app.js:61:25)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at createWindow (C:\Users\maren\AppData\Local\Programs\Budibase Builder\resources\app.asar\src\electron.js:50:18)
```
---
### Operating System Information:

Budibase Builder 0.8.3
Electron 10.1.3
win32 10.0.19041
Locale: en-US

Yes, I'm running with elevated permissions

**Comment by mestir** [comment]
@marens101

**Comment by shogunpurple** [comment]
@marens101 @mestir A few questions:

- does this happen every single time you open the builder? 
- Is this a brand new budibase installation, or have you just updated to the latest version from a previous version?

In any case, you should try the following:
- Restart your machine
- Kill any node processes on your machine that may be running at 4001
- Restart the builder
