### ISSUE TITLE
The database could not be created, the file already exists

### ISSUE THREAD

**Issue by pharindoko** [Budibase/budibase#1219]
**Describe the bug**
Running selfhosted budibase the app starts up on port 4002 and is accessible **but the couchdb fails.**
```
docker-compose --env-file hosting.properties up
```

**The database could not be created, the file already exists**
I rebuild the couchdb image but this does not help as well.

This log I get when starting docker-compose.

```bash
couch-init_1       |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
couch-init_1       |                                  Dload  Upload   Total   Spent    Left  Speed
100    95  100    95    0     0    475      0 --:--:{"error":"file_exists","reason":"The database could not be created, the file already exists."}
100    95  100    95    0     0    472      0 --:--:-- --:--:-- --:--:--   472
couchdb-service_1  | [notice] 2021-02-27T12:19:24.283209Z nonode@nohost <0.500.0> e31a65ae7d couchdb-service:5984 172.26.0.4 budibase PUT /_users 412 ok 171
couch-init_1       |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
couch-init_1       |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{"error":"file_exists","reason":"The database could not be created, the file already exists."}
100    95  100    95    0     0  47500      0 --:--:-- --:--:-- --:--:-- 47500
couch-init_1       | sh: fg: line 1: No current job
couchdb-service_1  | [notice] 2021-02-27T12:19:24.290392Z nonode@nohost <0.501.0> b3a6735a76 couchdb-service:5984 172.26.0.4 budibase PUT /_replicator 412 ok 1
hosting_couch-init_1 exited with code 2
couchdb-service_1  | [notice] 2021-02-27T12:19:29.051800Z nonode@nohost <0.249.0> -------- rexi_server : cluster stable
couchdb-service_1  | [notice] 2021-02-27T12:19:29.054802Z nonode@nohost <0.253.0> -------- rexi_buffer : cluster stable
couchdb-service_1  | [notice] 2021-02-27T12:19:38.300232Z nonode@nohost <0.618.0> f167438737 couchdb-service:5984 172.26.0.6 budibase GET /builder-config-db/hosting-doc? 404 ok 8
couchdb-service_1  | [notice] 2021-02-27T12:19:38.300852Z nonode@nohost <0.619.0> f2864c6fe7 couchdb-service:5984 172.26.0.6 budibase GET /pouch__all_dbs__/db_builder-config-db? 404 ok 8
app-service_1      | {
app-service_1      |   error: 'not_found',
app-service_1      |   reason: 'Database does not exist.',
app-service_1      |   status: 404,
app-service_1      |   name: 'not_found',
app-service_1      |   message: 'Database does not exist.',
app-service_1      |   docId: 'db_builder-config-db'
app-service_1      | }
couchdb-service_1  | [notice] 2021-02-27T12:19:38.309061Z nonode@nohost <0.620.0> b01514bbb4 couchdb-service:5984 172.26.0.6 budibase PUT /pouch__all_dbs__/db_builder-config-db 404 ok 2
couchdb-service_1  | [notice] 2021-02-27T12:19:38.376173Z nonode@nohost <0.621.0> 02e8901d9d couchdb-service:5984 172.26.0.5 budibase GET /_all_dbs 200 ok 65
couchdb-service_1  | [notice] 2021-02-27T12:19:38.389879Z nonode@nohost <0.633.0> 3463df84b8 couchdb-service:5984 172.26.0.6 budibase GET /worker/worker? 404 ok 1
couchdb-service_1  | [notice] 2021-02-27T12:19:38.390000Z nonode@nohost <0.634.0> 09a37374be couchdb-service:5984 172.26.0.6 budibase GET /pouch__all_dbs__/db_worker? 404 ok 1
app-service_1      | Trace: {
app-service_1      |   error: 'not_found',
app-service_1      |   reason: 'Database does not exist.',
app-service_1      |   status: 404,
app-service_1      |   name: 'not_found',
app-service_1      |   message: 'Database does not exist.',
app-service_1      |   docId: 'worker'
app-service_1      | }
app-service_1      |     at /app/src/api/index.js:50:13
app-service_1      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
app-service_1      | ERROR [1614428378390] (not_found/27 on 87960e0e924b):
app-service_1      |     error: "not_found"
app-service_1      |     reason: "Database does not exist."
app-service_1      |     status: 404
app-service_1      |     message: "Database does not exist."
app-service_1      |     docId: "worker"
app-service_1      |     req: {
app-service_1      |       "id": 2,
app-service_1      |       "method": "GET",
app-service_1      |       "url": "/worker/api/apps",
app-service_1      |       "headers": {
app-service_1      |         "x-budibase-auth": "budibase",
app-service_1      |         "accept": "*/*",
app-service_1      |         "user-agent": "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)",
app-service_1      |         "accept-encoding": "gzip,deflate",
app-service_1      |         "connection": "close",
app-service_1      |         "host": "localhost:4002"
app-service_1      |       },
app-service_1      |       "remoteAddress": "::ffff:172.26.0.1",
app-service_1      |       "remotePort": 40986
app-service_1      |     }
```

All is running on a AWS Linux EC2. I use this usually to work with VScode. Docker and docker-compose do work I know this from other projects.

I git-cloned the current master branch and executed docker-compose in the hosting folder

**Comment by shogunpurple** [comment]
@pharindoko Does couchDB actually not start up? Can you still successfully deploy to your self hosted instance? 

Thinking that the problem here may be https://github.com/Budibase/budibase/issues/1097. Will attempt to recreate your issue here and debug.

**Comment by pharindoko** [comment]
Hey @shogunpurple, the db service starts but runs into errors when I try to deploy...

„Database does not exist„

Please have a closer look to the logs above

**Comment by mike12345567** [comment]
Looks like there is an issue here, with the worker service on its endpoint `GET api/apps` which retrieves the list of apps to check for existing app names. When creating an app the system attempts to list the apps that already exist for the purposes of not allowing use of an existing app/URL but it appears something is going wrong here, the line suggesting that is:
```
couchdb-service_1  | [notice] 2021-02-27T12:19:38.389879Z nonode@nohost <0.633.0> 3463df84b8 couchdb-service:5984 172.26.0.6 budibase GET /worker/worker? 404 ok 1
couchdb-service_1  | [notice] 2021-02-27T12:19:38.390000Z nonode@nohost <0.634.0> 09a37374be couchdb-service:5984 172.26.0.6 budibase GET /pouch__all_dbs__/db_worker? 404 ok 1
```

It appears the endpoint is doing all `_all_dbs` call and in response is attempting to get two different DBs, `worker/worker` and `db_worker`. I will investigate to see if I can re-create this, @pharindoko out of interest had you been able to deploy apps at all to the self hosted platform or did it not work at all?

**Comment by pharindoko** [comment]
Hey  @mike12345567, it didn`t work at all to deploy the app on the self hosted platform.
So you were able to reproduce this error ?

**Comment by teamkarmix** [comment]
Please stop messaging me
