### ISSUE TITLE
Cannot download "https://github.com/Budibase/budibase/releases/download/v0.8.9/Budibase-Builder-Setup-0.8.9.exe", status 404: 

### ISSUE THREAD

**Issue by DaniDicki** [Budibase/budibase#1300]
### Error that occurred when using the budibase builder:
```
Error: Cannot download "https://github.com/Budibase/budibase/releases/download/v0.8.9/Budibase-Builder-Setup-0.8.9.exe", status 404: 
    at ClientRequest.<anonymous> (C:\Users\Usuario\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:280:26)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6157)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:482:12)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:137:15)
```
### Operating System Information:
---

Budibase Builder 0.8.5
Electron 10.1.3
win32 10.0.19042
Locale: es

**Comment by kevmodrome** [comment]
Hi Dani!

Looks like the URL to the download is not correct there. I've gone ahead and escalated the issue.

In the meantime you can download the builder latest builder from here: https://github.com/Budibase/budibase/releases/download/v0.8.9/Budibase-Builder-Setup-0.8.9-signed.exe

**Comment by shogunpurple** [comment]
This one should now be resolved - the URL has been updated. Thanks!
