### ISSUE TITLE
sha512 checksum mismatch, expected BbMLdyFoc36mppiraE6cmx+B+L0Gr8NPfjJMwCQ5KoEzMqaw23uFiJybYss/3YpQVBdwKE4r55D28MUM1WY1Gg==, got DL/hxnsFWiNKLBMdyZpnBdl3TfX6hrkz35qi2hpcdEbbkrOAOvS2mIF/mxUWuIZ9pwl4jwYRnE4c00pPAguZ1Q==

### ISSUE THREAD

**Issue by williamgh2019** [Budibase/budibase#1305]
### Error that occurred when using the budibase builder:
```
Error: sha512 checksum mismatch, expected BbMLdyFoc36mppiraE6cmx+B+L0Gr8NPfjJMwCQ5KoEzMqaw23uFiJybYss/3YpQVBdwKE4r55D28MUM1WY1Gg==, got DL/hxnsFWiNKLBMdyZpnBdl3TfX6hrkz35qi2hpcdEbbkrOAOvS2mIF/mxUWuIZ9pwl4jwYRnE4c00pPAguZ1Q==
    at newError (C:\Users\sulov\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\index.js:212:17)
    at DigestTransform.validate (C:\Users\sulov\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:409:35)
    at DigestTransform._flush (C:\Users\sulov\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:393:14)
    at DigestTransform.prefinish (_stream_transform.js:142:10)
    at DigestTransform.emit (events.js:310:20)
    at DigestTransform.EventEmitter.emit (domain.js:482:12)
    at prefinish (_stream_writable.js:628:14)
    at finishMaybe (_stream_writable.js:636:5)
    at endWritable (_stream_writable.js:656:3)
    at DigestTransform.Writable.end (_stream_writable.js:595:5)
    at IncomingMessage.onend (_stream_readable.js:660:10)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:310:20)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
### Operating System Information:
---

Budibase Builder 0.8.5
Electron 10.1.3
win32 10.0.19042
Locale: en-US

**Comment by shogunpurple** [comment]
Should now be solved with latest release.
