### ISSUE TITLE
no pg_hba.conf entry for host "XX.XX.XX.XX", user "XXXXXXXXX", database "XXXXXXXX", SSL off

### ISSUE THREAD

**Issue by DomNeuner** [Budibase/budibase#1326]
### Notes

Trying to connect to a postgres managed DB on Digital Ocean. The error shows host IP as my local WAN IP instead of the ip/hostname for the external DB even though that's what I have listed in the config.

Also `SSL off` but `sslmode = require` is needed by DigitalOcean and I can't see anywhere to configure this.

Not quite sure where the issue is caused.
 
### Error that occurred when using the budibase builder:
```
error: no pg_hba.conf entry for host "XX.XX.XX.XX", user "XXXXXXXXX", database "XXXXXXXX", SSL off
    at Parser.parseErrorMessage (C:\Users\Dominick\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\Users\Dominick\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\Dominick\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Users\Dominick\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```
### Operating System Information:
---

Budibase Builder 0.8.9
Electron 10.1.3
win32 10.0.19042
Locale: en-GB

**Comment by DomNeuner** [comment]
Hey, any ideas on this at all? 👋

**Comment by shogunpurple** [comment]
Hi @DomNeuner - I'll investigate this one. Did you use this service?

https://www.digitalocean.com/products/managed-databases-postgresql/

**Comment by niwasmala** [comment]
Hi, i'm having similar problem. I'm using heroku postgres database. Is there any way to configure ssl used in database connection?

**Comment by DomNeuner** [comment]
Hey @shogunpurple - yep, it's a DO managed DB.

My initial assumption is that it needs SSL to be required and there was no way to configure it that I could see.

**Comment by shogunpurple** [comment]
You can use the `ssl` option in the postgres connector now, so this should be addressed. I tested it with a postgres instance running in DO. Thanks for raising!

**Comment by jwillmer** [comment]
I can't see the option to disable SSL in the latest docker image @shogunpurple :
![image](https://user-images.githubusercontent.com/1503577/120319573-774e9180-c2e1-11eb-9d52-6b4f148b74ed.png)

**Comment by shogunpurple** [comment]
@jwillmer you need to add 

rejectUnauthorized: false

in the SSL settings.

**Comment by jwillmer** [comment]
which SSL settings? I don't see any field for it.

**Comment by shogunpurple** [comment]
- Click "Add" under the SSL header
- add rejectUnauthorized: true to the field displayed
- Save your data source

**Comment by jwillmer** [comment]
I save the following config, then I click on `AddQuery`. I add a query like `SELECT * FROM bla` and click on `Run Query`. Then I get the error.

![image](https://user-images.githubusercontent.com/1503577/120322660-f2657700-c2e4-11eb-8a1e-0b0422e8b522.png)

![image](https://user-images.githubusercontent.com/1503577/120322763-0f01af00-c2e5-11eb-858d-73ca56560756.png)

**Comment by jwillmer** [comment]
Works for me now @shogunpurple !
