### ISSUE TITLE
Row delete with foreign key

### ISSUE THREAD

**Issue by cgtms** [Budibase/budibase#13804]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.27.2

**Describe the bug**
When I am trying to delete row which has foreign key I am always facing problem. I also attach my database schema but it really doesnt matter of its structure.

```
2024-05-29T11:20:37.868529000Z INFO timestamp=2024-05-29T11:20:37.867Z service=@budibase/server pid=30 tenantId=default appId=app_4507b25cce4e471a961fd0a297c9e40f identityId=us_8daed9ceb3414dce95c3b1b0e567a489 identityType=user correlationId=38f89732-2003-4481-a394-78f93e45c403 msg=[SQL] [MYSQL2] query="select * from (select * from `clients` where `clients`.`id` = ? limit ?) as `clients`" values="2, 50000"
2024-05-29T11:20:37.904548000Z INFO timestamp=2024-05-29T11:20:37.903Z service=@budibase/server pid=30 tenantId=default appId=app_4507b25cce4e471a961fd0a297c9e40f identityId=us_8daed9ceb3414dce95c3b1b0e567a489 identityType=user correlationId=38f89732-2003-4481-a394-78f93e45c403 msg=[SQL] [MYSQL2] query="select * from (select * from `instances` where `instances`.`client_id` = ? limit ?) as `instances`" values="2, 50000"
2024-05-29T11:20:37.933171000Z ERROR timestamp=2024-05-29T11:20:37.932Z service=@budibase/server err={"type":"TypeError","message":"Cannot convert undefined or null to object","stack":"TypeError: Cannot convert undefined or null to object\n    at Function.entries (<anonymous>)\n    at parseBody (/app/dist/index.js:182577:36)\n    at InternalBuilder.update (/app/dist/index.js:183003:28)\n    at MySQLIntegration._query (/app/dist/index.js:183057:31)\n    at MySQLIntegration.queryWithReturning (/app/dist/index.js:183122:28)\n    at MySQLIntegration.query (/app/dist/index.js:196028:29)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 0)\n    at async ExternalRequest.removeRelationshipsToRow (/app/dist/index.js:230190:11)\n    at async ExternalRequest.run (/app/dist/index.js:230284:11)\n    at async Promise.all (index 0)\n    at async Object.bulkDestroy (/app/dist/index.js:230401:21)\n    at async deleteRows (/app/dist/index.js:236683:27)\n    at async destroy12 (/app/dist/index.js:236704:17)\n    at async cleanup_default (/app/dist/index.js:181139:20)\n    at async /app/node_modules/koa-compress/lib/index.js:38:5\n    at async errorHandling (/app/dist/index.js:156666:5)\n    at async /app/node_modules/koa-mount/index.js:52:26\n    at async userAgent (/app/node_modules/koa-useragent/dist/index.js:12:5)"} pid=30 tenantId=default correlationId=38f89732-2003-4481-a394-78f93e45c403 msg=Got 400 response code
2024-05-29T11:20:37.938713000Z INFO timestamp=2024-05-29T11:20:37.933Z service=@budibase/server req={"method":"DELETE","url":"/api/datasource_plus_4bd3a1bf2be04a20b652e03a1285586a__clients/rows","correlationId":"38f89732-2003-4481-a394-78f93e45c403"} res={"status":500} err={"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n    at ServerResponse.onResFinished (/app/dist/index.js:156475:45)\n    at ServerResponse.emit (node:events:531:35)\n    at ServerResponse.emit (node:domain:488:12)\n    at ServerResponse.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/server.js:36:19)\n    at onFinish (node:_http_outgoing:1031:10)\n    at callback (node:internal/streams/writable:757:21)\n    at afterWrite (node:internal/streams/writable:701:5)\n    at afterWriteTick (node:internal/streams/writable:687:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)"} responseTime=152 msg=request errored
```

[MySQL dump (1).sql.zip](https://github.com/Budibase/budibase/files/15483548/MySQL.dump.1.sql.zip)

**Comment by mad4me** [comment]
I have pretty much the same issue, its giving me a error 500 everytime i try to delete a row, its reallly buggy and random, I ensured my MySQL i have pretty much normal database, but its just throwing random javascript or https errors. 

![image](https://github.com/Budibase/budibase/assets/54853465/f05af2a6-7a78-4887-a1f2-e9b086bd8a9a)

Would probably create a issue about this more elaborated.
