### ISSUE TITLE
sorry, too many clients already

### ISSUE THREAD

**Issue by legaljustus** [Budibase/budibase#1425]
### Error that occurred when using the budibase builder:
```
error: sorry, too many clients already
    at Parser.parseErrorMessage (C:\Users\justus darley\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\Users\justus darley\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\justus darley\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Users\justus darley\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```
### Operating System Information:
---

Budibase Builder 0.8.17
Electron 10.1.3
win32 10.0.19041
Locale: nl

**Comment by shogunpurple** [comment]
Addressed with https://github.com/Budibase/budibase/pull/1508. Thanks for this report!
