### ISSUE TITLE
Issue with SQL Trigger Causing 500 Error During Row Insertion

### ISSUE THREAD

**Issue by Gtchik** [Budibase/budibase#14653]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.32.8
  - App Version: 2.32.8

**Describe the bug**
I've created a trigger to add lines to a second table when a row is created in my strategy-group table: 
```sql
CREATE DEFINER=`admin`@`%` TRIGGER `after_strategy_groups_insert` AFTER INSERT ON `strategy_groups` FOR EACH ROW BEGIN
    -- Insérer la première ligne dans strategies
    INSERT INTO strategies (strategy_type, fk_strategy_groups_strategies)
    VALUES ('Complète', NEW.id);

    -- Insérer la deuxième ligne dans strategies
    INSERT INTO strategies (strategy_type, fk_strategy_groups_strategies)
    VALUES ('Personnalisée', NEW.id);

    -- Insérer la troisième ligne dans strategies
    INSERT INTO strategies (strategy_type, fk_strategy_groups_strategies)
    VALUES ('Économique', NEW.id);
END
```

The idea is to use this rather than the budibase automation to re-route the load and to make them systematic even if the creation is done from another channel. 
But since creating this trigger, I'm getting a 500 error when creating a row in my table:
<img width="1122" alt="image" src="https://github.com/user-attachments/assets/faae213e-cc48-4a71-b7c7-176a77dd8be0">
Error log in docker :
```
172.17.0.1 - - [27/Sep/2024:23:10:17 +0000] "POST /api/datasource_plus_61ce0944681f4e6aaee1241c6d5c5eeb__strategy_groups/rows HTTP/1.1" 500 69 "https://my.wedly-concept.com/app/pre-prod" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "89.3.20.188"
{"level":"ERROR","timestamp":"2024-09-27T23:10:17.681Z","service":"@budibase/server","err":{"type":"TypeError","message":"Cannot convert undefined or null to object","stack":"TypeError: Cannot convert undefined or null to object\n    at Function.entries (<anonymous>)\n    at InternalBuilder.parseBody (/app/dist/index.js:161662:42)\n    at InternalBuilder.update (/app/dist/index.js:162415:33)\n    at MySQLIntegration._query (/app/dist/index.js:162485:31)\n    at MySQLIntegration.queryWithReturning (/app/dist/index.js:162545:28)\n    at MySQLIntegration.query (/app/dist/index.js:205909:29)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 0)\n    at async ExternalRequest.handleManyRelationships (/app/dist/index.js:227875:9)\n    at async ExternalRequest.run (/app/dist/index.js:227996:11)\n    at async Object.save12 (/app/dist/index.js:228193:21)\n    at async save14 (/app/dist/index.js:232280:92)\n    at async cleanup_default (/app/dist/index.js:191769:20)\n    at async /node_modules/koa-compress/lib/index.js:38:5\n    at async errorHandling (/app/dist/index.js:159469:5)\n    at async /node_modules/koa-mount/index.js:52:26\n    at async userAgent (/node_modules/koa-useragent/dist/index.js:12:5)"},"pid":253,"tenantId":"default","correlationId":"c9866114-fc1c-4322-8192-4036717540ba","msg":"Got 400 response code"}
{"level":"INFO","timestamp":"2024-09-27T23:10:17.682Z","service":"@budibase/server","req":{"method":"POST","url":"/api/datasource_plus_61ce0944681f4e6aaee1241c6d5c5eeb__strategy_groups/rows","correlationId":"c9866114-fc1c-4322-8192-4036717540ba"},"res":{"status":500},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n    at ServerResponse.onResFinished (/app/dist/index.js:159255:45)\n    at ServerResponse.emit (node:events:531:35)\n    at ServerResponse.emit (node:domain:488:12)\n    at ServerResponse.emit (/node_modules/dd-trace/packages/datadog-instrumentations/src/http/server.js:36:19)\n    at onFinish (node:_http_outgoing:1031:10)\n    at callback (node:internal/streams/writable:764:21)\n    at afterWrite (node:internal/streams/writable:708:5)\n    at afterWriteTick (node:internal/streams/writable:694:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)"},"responseTime":90,"msg":"request errored"}
```
Note that when I delete the trigger this problem disappears completely. 
I've also noticed that I have the same problem when I want to delete a relationship from my strategy_group table: 
<img width="905" alt="image" src="https://github.com/user-attachments/assets/190171e0-7fcf-4b3a-a3ff-6e05a758ec24">

**To Reproduce**
1. Create two tables with a relationship 
2. Trigger to create children when a parent is created
3. try to create a new parent row

**Expected behavior**
No 500 error, row creation should not be impacted by a SQL trigger

**Desktop:**
 - OS: MacOS
 - Browser : Arc (Chromium)

I hope my bug is clear 😄

**Comment by Gtchik** [comment]
For your information, I've created a new trigger that performs an update or insert based on a condition. It seems that only the insert statement is returning a 500 error, because everything works fine when the trigger only performs an update

**Comment by Gtchik** [comment]
Directly link to the issue reported [here](https://github.com/Budibase/budibase/issues/14747#issue-2575812397).

The fix made by @mike12345567 has indeed resolved the issue, and my application is now functioning correctly again. However, I have some concerns regarding this feature, as Budibase removes the link between my new entity and the children created via the trigger.


The queries run on my DB are as follows:
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/3c05886f-cf94-4f1a-aeae-06902eff9e20">
In blue: creation of my row
In red: creation of the children via the trigger
In green: deletion performed by the handleManyRelationships() function

This behavior is blocking for me. Although this trigger could be turned into an automation in Budibase, I have another trigger that logs modified elements, and I don’t believe Budibase can handle that in any other way.

In fact, I don’t quite understand why the potential relationships are being deleted during the creation of a row, especially in the context of MySQL. From my understanding, MySQL prevents the creation of a row if the foreign key isn't linked to any entity. So, when the row is created, it should be impossible for it to already have children. Is there something I’m missing?

**Comment by jython-25inflated200** [comment]
@linear https://hcl9.github.io/i4iYcK3iuqeQIoLSlIZQecxvgDBR4gYZN0CzjLWqdQ20ql5YnGq4Ix/
