### ISSUE TITLE
Cannot download "https://github.com/Budibase/budibase/releases/download/v0.8.13/Budibase-Builder-Setup-0.8.13.exe", status 404: 

### ISSUE THREAD

**Issue by lcarrProactive** [Budibase/budibase#1624]
### Error that occurred when using the budibase builder:
```
Error: Cannot download "https://github.com/Budibase/budibase/releases/download/v0.8.13/Budibase-Builder-Setup-0.8.13.exe", status 404: 
    at ClientRequest.<anonymous> (C:\Users\lcarr\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:280:26)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6157)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:482:12)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:137:15)
```
### Operating System Information:
---

Budibase Builder 0.4.3
Electron 10.1.3
win32 10.0.18363
Locale: en-US

**Comment by shogunpurple** [comment]
@lcarrProactive The old budibase desktop builder has been decommissioned. Please read the guide at https://docs.budibase.com/getting-started to get your budibase instance up and running.

**Comment by lcarrProactive** [comment]
Thanks!
