### ISSUE TITLE
Error running `budi`: Error: Cannot find module './feature-flags'

### ISSUE THREAD

**Issue by kbakk** [Budibase/budibase#1669]
**Describe the bug**
Error when running `budi`:

```
budi
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module './feature-flags'
Require stack:
- /usr/local/lib/node_modules/@budibase/cli/node_modules/posthog-node/index.js
- /usr/local/lib/node_modules/@budibase/cli/src/analytics/Client.js
- /usr/local/lib/node_modules/@budibase/cli/src/analytics/index.js
- /usr/local/lib/node_modules/@budibase/cli/src/options.js
- /usr/local/lib/node_modules/@budibase/cli/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@budibase/cli/node_modules/posthog-node/index.js:10:32)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@budibase/cli/node_modules/posthog-node/index.js',
    '/usr/local/lib/node_modules/@budibase/cli/src/analytics/Client.js',
    '/usr/local/lib/node_modules/@budibase/cli/src/analytics/index.js',
    '/usr/local/lib/node_modules/@budibase/cli/src/options.js',
    '/usr/local/lib/node_modules/@budibase/cli/src/index.js'
  ]
}
```

**To Reproduce**
1. `npm i --verbose -g @budibase/cli@0.9.32`
2. `budi`

**Expected behavior**
No exception raised

**Install logs**
<details>
  <summary>output</summary>

```
npm i --verbose -g @budibase/cli@0.9.32
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/Cellar/node@14/14.17.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'i',
npm verb cli   '--verbose',
npm verb cli   '-g',
npm verb cli   '@budibase/cli@0.9.32'
npm verb cli ]
npm info using npm@6.14.13
npm info using node@v14.17.0
npm verb npm-session 3fa42dcbfe5d275c
npm http fetch GET 200 https://registry.npmjs.org/@budibase%2fcli 2125ms
npm http fetch GET 200 https://registry.npmjs.org/@budibase/cli/-/cli-0.9.32.tgz 1501ms
npm timing stage:loadCurrentTree Completed in 4406ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 59ms
npm http fetch GET 304 https://registry.npmjs.org/axios 60ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chalk 92ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/commander 110ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/docker-compose 111ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inquirer 114ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/randomstring 122ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lookpath 123ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/posthog-node 777ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pkg 780ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/follow-redirects 38ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/supports-color 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-styles 55ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-convert 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-name 43ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-flag 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yaml 42ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/cli-cursor 66ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/cli-width 67ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/external-editor 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/figures 77ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-escapes 82ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash 83ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/run-async 85ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rxjs 94ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ora 102ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mute-stream 104ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/through 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-ansi 58ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/type-fest 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/restore-cursor 39ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/signal-exit 39ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/onetime 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-fn 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tmp 42ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chardet 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/iconv-lite 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/safer-buffer 30ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/os-tmpdir 49ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 43ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/cli-spinners 38ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-interactive 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/log-symbols 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wcwidth 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 57ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-unicode-supported 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inherits 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 55ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/base64-js 39ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ieee754 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/util-deprecate 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/safe-buffer 36ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 36ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/defaults 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/clone 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tslib 33ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/emoji-regex 77ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/escodegen 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/into-stream 66ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-extra 68ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/globby 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minimist 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@babel%2fruntime 76ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@babel%2fparser 88ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 84ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/progress 55ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/resolve 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/multistream 784ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pkg-fetch 786ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/stream-meter 720ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/regenerator-runtime 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/esutils 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/optionator 49ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/source-map 55ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/estraverse 62ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/esprima 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/deep-is 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/type-check 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prelude-ls 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fast-levenshtein 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/levn 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/word-wrap 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/jsonfile 38ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/universalify 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/graceful-fs 57ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/dir-glob 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ignore 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fast-glob 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/slash 58ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/merge2 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/array-union 104ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/path-type 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/glob-parent 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/picomatch 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/micromatch 54ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@nodelib%2ffs.stat 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@nodelib%2ffs.walk 85ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fastq 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@nodelib%2ffs.scandir 72ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/run-parallel 68ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/queue-microtask 36ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/reusify 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-glob 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-extglob 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/braces 34ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fill-range 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/to-regex-range 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-number 29ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/p-is-promise 39ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/from2 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/core-util-is 39ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/process-nextick-args 49ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/request-progress 37ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/request 39ms (from cache)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm http fetch GET 304 https://registry.npmjs.org/expand-template 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/byline 54ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/unique-temp-dir 759ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/combined-stream 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aws4 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-typedarray 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aws-sign2 71ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/forever-agent 71ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/caseless 77ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/extend 87ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/http-signature 87ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/form-data 97ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/har-validator 106ms (from cache)
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm http fetch GET 304 https://registry.npmjs.org/oauth-sign 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/json-stringify-safe 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isstream 71ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mime-types 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/performance-now 64ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tunnel-agent 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tough-cookie 54ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/qs 67ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/uuid 56ms (from cache)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm http fetch GET 304 https://registry.npmjs.org/delayed-stream 37ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/asynckit 29ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mime-db 34ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/har-schema 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ajv 64ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/uri-js 37ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fast-deep-equal 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/json-schema-traverse 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fast-json-stable-stringify 60ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/punycode 38ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/jsprim 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/assert-plus 43ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/sshpk 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/json-schema 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/extsprintf 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/verror 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ecc-jsbn 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/dashdash 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bcrypt-pbkdf 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/asn1 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/jsbn 57ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tweetnacl 58ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/getpass 67ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/psl 66ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/throttleit 31ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/uid2 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp 42ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 60ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 62ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 68ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pump 67ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rc 68ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 68ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 71ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 39ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 38ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/set-blocking 42ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/console-control-strings 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/delegates 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aproba 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-unicode 36ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wide-align 43ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/object-assign 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/code-point-at 34ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/number-is-nan 38ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/end-of-stream 33ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/once 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wrappy 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-json-comments 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ini 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/deep-extend 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 32ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 32ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 36ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/path-parse 31ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-core-module 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has 31ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/function-bind 43ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/component-type 32ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/remove-trailing-slash 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/md5 43ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/join-component 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/axios-retry 55ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ms 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-retry-allowed 34ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/crypt 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-buffer 49ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/charenc 57ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/array-uniq 34ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/randombytes 34ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 6895ms
npm timing stage:loadIdealTree Completed in 7001ms
npm timing stage:generateActionsToTake Completed in 13ms
npm verb correctMkdir /Users/krisb/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/krisb/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
npm timing action:extract Completed in 20ms
npm info lifecycle @budibase/cli@0.9.30~preuninstall: @budibase/cli@0.9.30
npm info lifecycle @budibase/cli@0.9.30~uninstall: @budibase/cli@0.9.30
npm verb unbuild rmStuff @budibase/cli@0.9.30 from /usr/local/lib/node_modules
npm info lifecycle @budibase/cli@0.9.30~postuninstall: @budibase/cli@0.9.30
npm timing action:unbuild Completed in 9ms
npm timing action:remove Completed in 47ms
npm timing action:finalize Completed in 56ms
npm timing action:refresh-package-json Completed in 15ms
npm info lifecycle @budibase/cli@0.9.32~preinstall: @budibase/cli@0.9.32
npm timing action:preinstall Completed in 1ms
npm info linkStuff @budibase/cli@0.9.32
npm verb linkBins [ { budi: 'src/index.js' }, '/usr/local/bin', true ]
/usr/local/bin/budi -> /usr/local/lib/node_modules/@budibase/cli/src/index.js
npm timing action:build Completed in 6ms
npm info lifecycle @budibase/cli@0.9.32~install: @budibase/cli@0.9.32
npm timing action:install Completed in 0ms
npm info lifecycle @budibase/cli@0.9.32~postinstall: @budibase/cli@0.9.32
npm timing action:postinstall Completed in 0ms
npm verb unlock done using /Users/krisb/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
npm timing stage:executeActions Completed in 166ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 11590ms
+ @budibase/cli@0.9.32
updated 1 package in 11.592s
npm verb exit [ 0, true ]
npm timing npm Completed in 13525ms
npm info ok
```  

</details>

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - node --version -> v14.17.0
 - npm --version -> 6.14.13

**Additional context**
Same issue with node v16.3.0 or npm 7.16.0

**Comment by shogunpurple** [comment]
Thanks @kbakk - we've just had another report of this happening and have identified the issue.

One of our dependencies was being updated automatically and they have introduced a breaking change. I've pushed the fix, and when it's published (about 10 minutes) you can run:

`npm i -g @budibase/cli` to update your CLI

then just `budi hosting --init`

thanks for the report!

**Comment by kbakk** [comment]
Thanks, reinstalling now fixed it :)
