### ISSUE TITLE
Cannot find latest-mac.yml in the latest release artifacts

### ISSUE THREAD

**Issue by ddresch** [Budibase/budibase#1698]
### Error that occurred when using the budibase builder:
```
Error: Cannot find latest-mac.yml in the latest release artifacts (https://github.com/Budibase/budibase/releases/download/v0.9.44/latest-mac.yml): HttpError: 404 
"method: GET url: https://github.com/Budibase/budibase/releases/download/v0.9.44/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "status": "404",
  "server": "GitHub.com",
  "date": "Fri, 11 Jun 2021 08:46:06 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "ED27:CF83:1542C13:15C2450:60C322CD"
}
    at createHttpError (/Applications/Budibase Builder.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (/Applications/Budibase Builder.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:169:14)
    at ClientRequest.<anonymous> (/Applications/Budibase Builder.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6157)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:482:12)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:137:15)
    at newError (/Applications/Budibase Builder.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:212:17)
    at GitHubProvider.getLatestVersion (/Applications/Budibase Builder.app/Contents/Resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:135:50)
    at async MacUpdater.getUpdateInfoAndProvider (/Applications/Budibase Builder.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:487:13)
    at async MacUpdater.doCheckForUpdates (/Applications/Budibase Builder.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:503:20)
```
### Operating System Information:
---

Budibase Builder 0.7.6
Electron 10.1.3
darwin 17.7.0
Locale: de

**Comment by shogunpurple** [comment]
@ddresch the electron app is deprecated and no longer maintained - it says so in the app itself.

The web experience is the latest and maintained version of budibase. Please follow the guide here to set up your environment at https://docs.budibase.com/.
