### ISSUE TITLE
Cannot find latest.yml in the latest release artifacts

### ISSUE THREAD

**Issue by stagefright5** [Budibase/budibase#1730]
### Error that occurred when using the budibase builder:
```
Error: Cannot find latest.yml in the latest release artifacts (https://github.com/Budibase/budibase/releases/download/v0.9.44/latest.yml): HttpError: 404 
"method: GET url: https://github.com/Budibase/budibase/releases/download/v0.9.44/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "status": "404",
  "server": "GitHub.com",
  "date": "Fri, 18 Jun 2021 05:05:08 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "CBDC:54D1:48434D:4E001A:60CC29A8"
}
    at createHttpError (C:\Users\sanka\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (C:\Users\sanka\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:169:14)
    at ClientRequest.<anonymous> (C:\Users\sanka\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6157)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:482:12)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:137:15)
    at newError (C:\Users\sanka\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\index.js:212:17)
    at GitHubProvider.getLatestVersion (C:\Users\sanka\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\electron-updater\out\providers\GitHubProvider.js:135:50)
    at async NsisUpdater.getUpdateInfoAndProvider (C:\Users\sanka\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:487:13)
    at async NsisUpdater.doCheckForUpdates (C:\Users\sanka\AppData\Local\Programs\Budibase Builder\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:503:20)
```
### Operating System Information:
---

Budibase Builder 0.8.17
Electron 10.1.3
win32 10.0.19043
Locale: en-US

**Comment by shogunpurple** [comment]
@stagefright5 the electron app is no longer maintained. Please upgrade your installation to use the web based builder.

You can follow along here:

https://docs.budibase.com/getting-started
