### ISSUE TITLE
Airtable queries are always empty

### ISSUE THREAD

**Issue by aantn** [Budibase/budibase#1740]
I can't figure out how to add an Airtable query.

I have the following errors in the docker logs which may or may not be related:
```
ERROR    [1624026320238] (29 on 21aa2f4d12a1): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
ERROR    [1624028930330] (29 on 21aa2f4d12a1): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
```

**Comment by aantn** [comment]
Closing this, I was using a human-readable name for the `base` parameter. Switching it to the Airtable base-id (randomcharsxjfkdaf) fixed it.

**Comment by Narvey** [comment]
I changed it to human-readable and still always get no results.
