### ISSUE TITLE
MySQL table names escaping

### ISSUE THREAD

**Issue by misterx** [Budibase/budibase#3314]
**Describe the bug**
I'm getting error when I am trying to add mysql datasource with table name `groups`. Looks like table names are not properly escaped.

**To Reproduce**
1. Go to 'Data'
2. Click on 'Add datasource'
3. Select Mysql and enter credentials
3. See error ' Error saving datasource: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups' at line 1" '

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser chrome
 - Version 95

**Additional context**
```
bbapps                | Trace: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntaxto use near 'groups' at line 1
bbapps                |     at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:728:17)
bbapps                |     at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
bbapps                |     at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:456:32)
bbapps                |     at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:85:12)
bbapps                |     at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
bbapps                |     at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:92:25)
bbapps                |     at Socket.emit (events.js:314:20)
bbapps                |     at Socket.EventEmitter.emit (domain.js:483:12)
bbapps                |     at addChunk (_stream_readable.js:297:12)
bbapps                |     at readableAddChunk (_stream_readable.js:272:9)
bbapps                |     at Socket.Readable.push (_stream_readable.js:213:10)
bbapps                |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
bbapps                |     at TCP.callbackTrampoline (internal/async_hooks.js:126:14) {
bbapps                |   code: 'ER_PARSE_ERROR',
bbapps                |   errno: 1064,
bbapps                |   sqlState: '42000',
bbapps                |   sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups' at line 1",
bbapps                |   sql: 'DESCRIBE groups;'
bbapps                | }
bbapps                |     at /app/dist/api/index.js:69:21
bbapps                |     at Generator.throw (<anonymous>)
bbapps                |     at rejected (/app/dist/api/index.js:6:65)
bbapps                |     at runMicrotasks (<anonymous>)
bbapps                |     at processTicksAndRejections (internal/process/task_
queues.js:97:5)
```

**Comment by mike12345567** [comment]
issue resolved in #3738 - will be released next week.
