### ISSUE TITLE
Dev environment not working as described in Contributing.md

### ISSUE THREAD

**Issue by melanki** [Budibase/budibase#3731]
**Describe the bug**
Does not seem like yarn dev runs docker with variables from hosting.properties.
When adding properties manually to docker-compose.dev.yaml i get past couchdb3 container crashing and server + builder not connecting to redis.

Going to localhost:10000 redirects me to localhost:10000/builder but gives me the "This site can’t be reached" screen.

**To Reproduce**
1. Git clone budibase
2. Yarn
3. Yarn bootstrap
4. Yarn dev

**Expected behavior**
yarn dev should start dockers with settings from hosting.properties, and I should be able to access localhost:10000/builder

**Desktop (please complete the following information):**
 - macOS
 - Chrome
 - Latest version from git

**Comment by melanki** [comment]
```
yarn run v1.22.17
$ yarn run kill-port && lerna link && lerna run --parallel dev:builder --concurrency 1
$ kill-port 4001
Process on port 4001 killed
lerna notice cli v3.14.1
lerna info Symlinking packages and binaries
lerna notice cli v3.14.1
lerna info Executing command in 5 packages: "yarn run dev:builder"
@budibase/builder: $ routify -c dev:vite
@budibase/client: $ rollup -cw
@budibase/string-templates: $ tsc && rollup -cw
@budibase/server: $ yarn run dev:stack:up && nodemon
@budibase/worker: $ npm run dev:stack:init && nodemon
@budibase/builder: [Routify] Watching src/pages
@budibase/builder: [Routify] Generated routes in 1 ms
@budibase/server: $ node scripts/dev/manage.js up
@budibase/client: rollup v2.60.0
@budibase/client: bundles src/index.js → dist/budibase-client.js...
@budibase/worker: > @budibase/worker@1.0.8-alpha.0 dev:stack:init
@budibase/worker: > node ./scripts/dev/manage.js init
@budibase/builder: > @budibase/builder@1.0.8-alpha.0 dev:vite
@budibase/builder: > vite --host 0.0.0.0
@budibase/worker: Done! 🎉
@budibase/server: Spinning up your budibase dev environment... 🔧✨
@budibase/worker: [nodemon] 2.0.15
@budibase/worker: [nodemon] to restart at any time, enter `rs`
@budibase/worker: [nodemon] watching path(s): src/**/* ../auth/**/*
@budibase/worker: [nodemon] watching extensions: js,mjs,json
@budibase/worker: [nodemon] starting `node src/index.js`
@budibase/server: time="2021-12-08T21:15:17+01:00" level=warning msg="The \"MAIN_PORT\" variable is not set. Defaulting to a blank string."
@budibase/server: time="2021-12-08T21:15:17+01:00" level=warning msg="The \"COUCH_DB_PORT\" variable is not set. Defaulting to a blank string."
@budibase/server: time="2021-12-08T21:15:17+01:00" level=warning msg="The \"COUCH_DB_USER\" variable is not set. Defaulting to a blank string."
@budibase/server: time="2021-12-08T21:15:17+01:00" level=warning msg="The \"COUCH_DB_PASSWORD\" variable is not set. Defaulting to a blank string."
@budibase/server: time="2021-12-08T21:15:17+01:00" level=warning msg="The \"MINIO_PORT\" variable is not set. Defaulting to a blank string."
@budibase/server: time="2021-12-08T21:15:17+01:00" level=warning msg="The \"MINIO_ACCESS_KEY\" variable is not set. Defaulting to a blank string."
@budibase/server: time="2021-12-08T21:15:17+01:00" level=warning msg="The \"MINIO_SECRET_KEY\" variable is not set. Defaulting to a blank string."
@budibase/server: Network hosting_default  Creating
@budibase/server: Network hosting_default  Created
@budibase/server: Volume "hosting_couchdb3_data"  Creating
@budibase/server: Volume "hosting_couchdb3_data"  Created
@budibase/server: Volume "hosting_redis_data"  Creating
@budibase/server: Volume "hosting_redis_data"  Created
@budibase/server: Volume "hosting_minio_data"  Creating
@budibase/server: Volume "hosting_minio_data"  Created
@budibase/server: Container budi-minio-dev  Creating
@budibase/server: Container budi-redis-dev  Creating
@budibase/server: Container budi-couchdb-dev  Creating
@budibase/builder:   vite v2.6.14 dev server running at:
@budibase/builder:   > Local:    http://localhost:3000/builder/
@budibase/builder:   > Network:  http://192.168.1.184:3000/builder/
@budibase/builder:   ready in 448ms.
@budibase/server: Container budi-couchdb-dev  Created
@budibase/server: Container budi-couchdb-init-dev  Creating
@budibase/server: Container budi-redis-dev  Created
@budibase/server: Container budi-minio-dev  Created
@budibase/server: Container budi-envoy-dev  Creating
@budibase/server: Container budi-couchdb-init-dev  Created
@budibase/server: Container budi-envoy-dev  Created
@budibase/server: Container budi-couchdb-dev  Starting
@budibase/server: Container budi-minio-dev  Starting
@budibase/server: Container budi-redis-dev  Starting
@budibase/worker: Error: listen EADDRINUSE: address already in use :::4002
@budibase/worker:     at Server.setupListenHandle [as _listen2] (net.js:1320:16)
@budibase/worker:     at listenInCluster (net.js:1368:12)
@budibase/worker:     at Server.listen (net.js:1454:7)
@budibase/worker:     at Object.<anonymous> (/Users/marensius/Dev/Canon/budibase/packages/worker/src/index.js:64:25)
@budibase/worker:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
@budibase/worker:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
@budibase/worker:     at Module.load (internal/modules/cjs/loader.js:937:32)
@budibase/worker:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
@budibase/worker:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
@budibase/worker:     at internal/main/run_main_module.js:17:47 {
@budibase/worker:   code: 'EADDRINUSE',
@budibase/worker:   errno: -48,
@budibase/worker:   syscall: 'listen',
@budibase/worker:   address: '::',
@budibase/worker:   port: 4002
@budibase/worker: }
@budibase/worker: [nodemon] clean exit - waiting for changes before restart
@budibase/server: Container budi-minio-dev  Started
@budibase/server: Container budi-couchdb-dev  Started
@budibase/server: Container budi-redis-dev  Started
@budibase/server: Container budi-envoy-dev  Starting
@budibase/server: Container budi-couchdb-init-dev  Starting
@budibase/builder: 21:15:20 [vite-plugin-svelte] /Users/marensius/Dev/Canon/budibase/packages/bbui/src/Label/Label.svelte:20:6 A11y: on:mouseover must be accompanied by on:focus
@budibase/server: Container budi-couchdb-init-dev  Started
@budibase/server: Container budi-envoy-dev  Started
@budibase/server: Done! 🎉
@budibase/server: [nodemon] 2.0.15
@budibase/server: [nodemon] to restart at any time, enter `rs`
@budibase/server: [nodemon] watching path(s): src/**/* ../auth/**/*
@budibase/server: [nodemon] watching extensions: js,ts,json
@budibase/server: [nodemon] starting `ts-node src/index.ts`
@budibase/string-templates: rollup v2.60.0
@budibase/string-templates: bundles src/index.mjs → dist/bundle.mjs...
@budibase/builder: 21:15:28 [vite-plugin-svelte] /Users/marensius/Dev/Canon/budibase/packages/builder/src/components/backend/DatasourceNavigator/modals/DatasourceConfigModal.svelte:79:1 Unused CSS selector "*"
@budibase/builder: 21:15:30 [vite-plugin-svelte] /Users/marensius/Dev/Canon/budibase/packages/builder/src/components/backend/DataTable/modals/ImportModal.svelte:43:1 Unused CSS selector "*"
@budibase/string-templates: created dist/bundle.mjs in 9s
@budibase/client: (!) Circular dependencies
@budibase/client: src/components/Component.svelte -> src/components/app/index.js -> src/components/app/blocks/index.js -> src/components/app/blocks/TableBlock.svelte -> src/components/BlockComponent.svelte -> src/components/Component.svelte
@budibase/client: src/stores/index.js -> src/stores/auth.js -> src/api/index.js -> src/api/rows.js -> src/stores/index.js
@budibase/client: src/stores/index.js -> src/stores/auth.js -> src/api/index.js -> src/api/rows.js -> src/api/api.js -> src/stores/index.js
@budibase/client: ...and 6 more
@budibase/client: (!) Plugin svelte: A11y: on:mouseover must be accompanied by on:focus
@budibase/client: ../bbui/src/Label/Label.svelte
@budibase/client: 18:     </label>
@budibase/client: 19:     <div class="icon-container">
@budibase/client: 20:       <div
@budibase/client:           ^
@budibase/client: 21:         class="icon"
@budibase/client: 22:         on:mouseover={() => (showTooltip = true)}
@budibase/client: created dist/budibase-client.js in 17.3s
@budibase/server: Budibase running on {"address":"::","family":"IPv6","port":4001}
```

**Comment by melanki** [comment]
With a clean install without modifying docker files I am getting

`Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379`

I can see that redis docker is on a restart loop due to

```
*** FATAL CONFIG FILE ERROR (Redis 6.2.6) ***

Reading the configuration file, at line 2

>>> 'requirepass'

wrong number of arguments
```

**Comment by shogunpurple** [comment]
Hi @melanki 

> Error: listen EADDRINUSE: address already in use :::4002

It seems like something is already running on this port on your machine. Try killing it and running again.
`kill -9 $(lsof -ti :4002)`

It also looks like you don't have any environment variables set - you might need to run `yarn setup` before your `yarn dev` command.

**Comment by melanki** [comment]
@shogunpurple 

I killed the process occupying 4002 yesterday after posting, still the same.

Also ran `yarn setup`, but the settings from hosting.properties does not propagte to env files.

I finally managed to get everything up and running without any errors in console and docker by manually modifiying dev dockerfile and env files. But still cant access `localhost:10000`

**Comment by melanki** [comment]
Tried again on Ubuntu machine as I was thinking the M1 processor might be causing the issues somehow.

Ran yarn setup on the Ubuntu machine, getting the same issue (Redis connection failed)

**Comment by shogunpurple** [comment]
Hi @melanki - thanks.

I cannot seem to recreate this, on a fresh linux VM.

Could you send the output of `yarn dev` again when you run on your ubuntu machine?

> I finally managed to get everything up and running without any errors in console and docker by manually modifiying dev  dockerfile and env files. But still cant access localhost:10000 

Are there any errors in the logs? 

Also, you mention `hosting.properties`, but it's not used in the dev setup. They are managed by the `manage.js` script that should be run by `yarn dev`.

I would recommend starting clean by cloning budibase into a different directory, and running through step by step. After running `yarn dev`, you should have:
`packages/server/.env`
`packages/worker/.env`

With all the configuration required. If you run `yarn dev` and these files are not created, can you please try and run:
`cd packages/server`
`yarn dev:stack:init`

and let me know the output of that command?

**Comment by melanki** [comment]
@shogunpurple Here is the output of `yarn setup & yarn dev` in Ubuntu from a fresh clone.

I see that builder is thrwoing EACCES on Vite, but that is something I fixed on my macOS build, and I still could not access the builder.

```
root@ubuntu:/home/marensius/Dev/budibase# yarn dev
yarn run v1.22.17
$ yarn run kill-port && lerna link && lerna run --parallel dev:builder --concurrency 1
$ kill-port 4001
Process on port 4001 killed
lerna notice cli v3.14.1
lerna info Symlinking packages and binaries
lerna notice cli v3.14.1
lerna info Executing command in 5 packages: "yarn run dev:builder"
@budibase/builder: $ routify -c dev:vite
@budibase/client: $ rollup -cw
@budibase/worker: $ npm run dev:stack:init && nodemon
@budibase/server: $ yarn run dev:stack:up && nodemon
@budibase/string-templates: $ tsc && rollup -cw
@budibase/builder: [Routify] Watching src/pages
@budibase/builder: [Routify] Generated routes in 13 ms
@budibase/server: $ node scripts/dev/manage.js up
@budibase/client: rollup v2.60.0
@budibase/client: bundles src/index.js → dist/budibase-client.js...
@budibase/builder: > @budibase/builder@1.0.9-alpha.1 dev:vite
@budibase/builder: > vite --host 0.0.0.0
@budibase/worker: > @budibase/worker@1.0.9-alpha.1 dev:stack:init
@budibase/worker: > node ./scripts/dev/manage.js init
@budibase/server: Spinning up your budibase dev environment... 🔧✨
@budibase/worker: Done! 🎉
@budibase/worker: [nodemon] 2.0.15
@budibase/worker: [nodemon] to restart at any time, enter `rs`
@budibase/worker: [nodemon] watching path(s): src/**/* ../auth/**/*
@budibase/worker: [nodemon] watching extensions: js,mjs,json
@budibase/worker: [nodemon] starting `node src/index.js`
@budibase/server: The MINIO_PORT variable is not set. Defaulting to a blank string.
@budibase/server: The MINIO_ACCESS_KEY variable is not set. Defaulting to a blank string.
@budibase/server: The MINIO_SECRET_KEY variable is not set. Defaulting to a blank string.
@budibase/server: The MAIN_PORT variable is not set. Defaulting to a blank string.
@budibase/server: The COUCH_DB_PASSWORD variable is not set. Defaulting to a blank string.
@budibase/server: The COUCH_DB_USER variable is not set. Defaulting to a blank string.
@budibase/server: The COUCH_DB_PORT variable is not set. Defaulting to a blank string.
@budibase/server: The REDIS_PASSWORD variable is not set. Defaulting to a blank string.
@budibase/server: The REDIS_PORT variable is not set. Defaulting to a blank string.
@budibase/server: The Compose file './docker-compose.dev.yaml' is invalid because:
@budibase/server: services.proxy-service.ports contains an invalid type, it should be a number, or an object
@budibase/server: services.couchdb-service.ports contains an invalid type, it should be a number, or an object
@budibase/server: services.redis-service.ports contains an invalid type, it should be a number, or an object
@budibase/server: services.minio-service.ports contains an invalid type, it should be a number, or an object
@budibase/server: Something went wrong while managing budibase dev environment: undefined
@budibase/builder: error when starting dev server:
@budibase/builder: Error: EACCES: permission denied, mkdir '/home/marensius/Dev/budibase/packages/builder/node_modules/.vite'
@budibase/builder:     at Object.mkdirSync (node:fs:1334:3)
@budibase/builder:     at optimizeDeps (/home/marensius/Dev/budibase/packages/builder/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:63025:21)
@budibase/builder:     at runOptimize (/home/marensius/Dev/budibase/packages/builder/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66904:54)
@budibase/builder:     at Server.httpServer.listen (/home/marensius/Dev/budibase/packages/builder/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66920:27)
@budibase/builder:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
@budibase/server: [nodemon] 2.0.15
@budibase/server: [nodemon] to restart at any time, enter `rs`
@budibase/server: [nodemon] watching path(s): src/**/* ../auth/**/*
@budibase/server: [nodemon] watching extensions: js,ts,json
@budibase/server: [nodemon] starting `ts-node src/index.ts`
@budibase/worker: Worker running on {"address":"::","family":"IPv6","port":4002}
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/string-templates: rollup v2.60.0
@budibase/string-templates: bundles src/index.mjs → dist/bundle.mjs...
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Did not successfully connect in timeout
@budibase/worker: Redis connection failed - undefined
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/string-templates: created dist/bundle.mjs in 1m 41.7s
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
@budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379
```

**Comment by mike12345567** [comment]
Hi @melanki - could you try cloning the `develop` branch now? I think one of the symlinks may not have been getting initialised correctly which contained some environment variables required for development.

**Comment by melanki** [comment]
@mike12345567 

This seems to have solved the ports & other settings not propagating correctly, but I am still getting persmission issues for mkdir.

```
yarn dev
yarn run v1.22.17
$ yarn run kill-port && lerna link && lerna run --parallel dev:builder --concurrency 1
$ kill-port 4001
Process on port 4001 killed
lerna notice cli v3.14.1
lerna info Symlinking packages and binaries
lerna notice cli v3.14.1
lerna info Executing command in 5 packages: "yarn run dev:builder"
@budibase/builder: $ routify -c dev:vite
@budibase/client: $ rollup -cw
@budibase/string-templates: $ tsc && rollup -cw
@budibase/server: $ yarn run dev:stack:up && nodemon
@budibase/worker: $ npm run dev:stack:init && nodemon
@budibase/builder: [Routify] Watching src/pages
@budibase/builder: [Routify] Generated routes in 1 ms
@budibase/server: $ node scripts/dev/manage.js up
@budibase/client: rollup v2.60.0
@budibase/client: bundles src/index.js → dist/budibase-client.js...
@budibase/worker: > @budibase/worker@1.0.13-alpha.1 dev:stack:init
@budibase/worker: > node ./scripts/dev/manage.js init
@budibase/builder: > @budibase/builder@1.0.13-alpha.1 dev:vite
@budibase/builder: > vite --host 0.0.0.0
@budibase/server: Spinning up your budibase dev environment... 🔧✨
@budibase/worker: Done! 🎉
@budibase/worker: [nodemon] 2.0.15
@budibase/worker: [nodemon] to restart at any time, enter `rs`
@budibase/worker: [nodemon] watching path(s): src/**/* ../auth/**/*
@budibase/worker: [nodemon] watching extensions: js,mjs,json
@budibase/worker: [nodemon] starting `node src/index.js`
@budibase/builder: error when starting dev server:
@budibase/builder: Error: EACCES: permission denied, mkdir '/Users/marensius/Dev/Canon/budibaseretest/budibase/packages/builder/node_modules/.vite'
@budibase/builder:     at Object.mkdirSync (fs.js:1009:3)
@budibase/builder:     at optimizeDeps (/Users/marensius/Dev/Canon/budibaseretest/budibase/packages/builder/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:63025:21)
@budibase/builder:     at runOptimize (/Users/marensius/Dev/Canon/budibaseretest/budibase/packages/builder/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66904:54)
@budibase/builder:     at Server.httpServer.listen (/Users/marensius/Dev/Canon/budibaseretest/budibase/packages/builder/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66920:27)
@budibase/builder:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
@budibase/server: Container budi-couchdb-dev  Running
@budibase/server: Container budi-couchdb-init-dev  Created
@budibase/server: Container budi-redis-dev  Running
@budibase/server: Container budi-minio-dev  Running
@budibase/server: Container budi-envoy-dev  Running
@budibase/server: Container budi-couchdb-init-dev  Starting
@budibase/worker: Worker running on {"address":"::","family":"IPv6","port":4002}
@budibase/server: Container budi-couchdb-init-dev  Started
@budibase/server: Done! 🎉
@budibase/server: [nodemon] 2.0.15
@budibase/server: [nodemon] to restart at any time, enter `rs`
@budibase/server: [nodemon] watching path(s): src/**/* ../auth/**/*
@budibase/server: [nodemon] watching extensions: js,ts,json
@budibase/server: [nodemon] starting `ts-node src/index.ts`
@budibase/string-templates: rollup v2.60.0
@budibase/string-templates: bundles src/index.mjs → dist/bundle.mjs...
@budibase/string-templates: created dist/bundle.mjs in 7.3s
@budibase/client: (!) Circular dependencies
@budibase/client: src/components/Component.svelte -> src/components/app/index.js -> src/components/app/blocks/index.js -> src/components/app/blocks/TableBlock.svelte -> src/components/BlockComponent.svelte -> src/components/Component.svelte
@budibase/client: src/stores/index.js -> src/stores/auth.js -> src/api/index.js -> src/api/rows.js -> src/stores/index.js
@budibase/client: src/stores/index.js -> src/stores/auth.js -> src/api/index.js -> src/api/rows.js -> src/api/api.js -> src/stores/index.js
@budibase/client: ...and 6 more
@budibase/client: (!) Plugin svelte: A11y: on:mouseover must be accompanied by on:focus
@budibase/client: ../bbui/src/Label/Label.svelte
@budibase/client: 18:     </label>
@budibase/client: 19:     <div class="icon-container">
@budibase/client: 20:       <div
@budibase/client:           ^
@budibase/client: 21:         class="icon"
@budibase/client: 22:         on:mouseover={() => (showTooltip = true)}
@budibase/client: created dist/budibase-client.js in 15.6s
@budibase/server: Budibase running on {"address":"::","family":"IPv6","port":4001}
```

**Comment by mike12345567** [comment]
Hi @melanki - this permissions issue, i'm not sure thats something we will have control over, in your Ubuntu environment you'll need to make sure that you own and have permission to the directory in which you've checked out the files (Git by default will simply take permissions from the directory it is being cloned to).

You can try `chown -R <yourusername>:<yourusername> ./<budibase directory>` - this should make sure that the ownership of the directory is as expected.

**Comment by melanki** [comment]
@mike12345567

Sure, I can fix this on my own.

But the same issue comes up in ubuntu and macOS, so thought maybe it might be something that could be fixed at repo level.

**Comment by mike12345567** [comment]
Hi @melanki - i'm also running Ubuntu (18.04) and I don't have any issue with cloning and initial setup. I'm wondering if its something to do with your Node version and the `fs` module, if something has changed around how `fs.mkdir` works with permissions, could you let me know what version of Node you're using?

**Comment by melanki** [comment]
@mike12345567 
I have v14.17.6 on my Macbook and v17 on my Ubuntu machine, thus very confused how i have the same issue on two different machines.
