### ISSUE TITLE
Curl and Swagger import are broken

### ISSUE THREAD

**Issue by Rory-Powell** [Budibase/budibase#4746]
**Describe the bug**

![Screenshot 2022-03-01 at 07 26 04](https://user-images.githubusercontent.com/8755148/156123881-f1698d84-65a6-4789-b4b9-5c1019d5be09.png)
![Screenshot 2022-03-01 at 07 25 50](https://user-images.githubusercontent.com/8755148/156123852-fa723439-cf1c-45ec-9219-4babd941c34c.png)

```
@budibase/server: Trace: TypeError: Cannot read property 'getInfo' of undefined
@budibase/server:     at RestImporter.<anonymous> (/Users/rpowell/dev/repos/budibase/packages/server/src/api/controllers/query/import/index.ts:34:24)
@budibase/server:     at Generator.next (<anonymous>)
@budibase/server:     at /Users/rpowell/dev/repos/budibase/packages/server/src/api/controllers/query/import/index.ts:8:71
@budibase/server:     at new Promise (<anonymous>)
@budibase/server:     at __awaiter (/Users/rpowell/dev/repos/budibase/packages/server/src/api/controllers/query/import/index.ts:4:12)
@budibase/server:     at RestImporter.getInfo (/Users/rpowell/dev/repos/budibase/packages/server/src/api/controllers/query/import/index.ts:33:45)
@budibase/server:     at /Users/rpowell/dev/repos/budibase/packages/server/src/api/controllers/query/index.js:52:33
@budibase/server:     at Generator.next (<anonymous>)
@budibase/server:     at fulfilled (/Users/rpowell/dev/repos/budibase/packages/server/src/api/controllers/query/index.js:5:58)
@budibase/server:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
@budibase/server:     at /Users/rpowell/dev/repos/budibase/packages/server/src/api/index.js:72:15
@budibase/server:     at Generator.throw (<anonymous>)
@budibase/server:     at rejected (/Users/rpowell/dev/repos/budibase/packages/server/src/api/index.js:6:65)
@budibase/server:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by Rory-Powell** [comment]
Fixed in `1.0.78`
