### ISSUE TITLE
problem with Webhook , error 500 TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by medvejonok79** [Budibase/budibase#5152]
Hi,

I am trying to set up a web hook between Espo CRM and Budibase. I have checked and the CRM works fine, does what it is meant to do. However there is an error 500 on the budibase side.
At first, it looked as though this was because some values in the JSON that was posted by the CRM were empty, but even filling every field with values, I still get the same error.

Here is the relevant section of the app log (run with docker-compose):

```
ERROR [1648544512399] (29 on XYZ): Cannot convert undefined or null to object
    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at /app/dist/api/controllers/webhook.js:73:33
        at Generator.next (<anonymous>)
        at fulfilled (/app/dist/api/controllers/webhook.js:5:58)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
INFO  [1648544412319] (29 on XYZ): request errored
    res: {
      "statusCode": 500,
      "headers": {
        "vary": "Accept-Encoding",
        "set-cookie": [
          "budibase:currentapp=XYZ**************XYZ; path=/; expires=Tue, 19 Jan 2038 03:14:07 GMT"
        ],
        "content-type": "application/json; charset=utf-8",
        "content-length": "69"
      }
    }
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:77:38)
              at ServerResponse.emit (events.js:412:35)
              at ServerResponse.emit (domain.js:475:12)
              at ServerResponse.emitted (/app/node_modules/emitter-listener/listener.js:134:21)
              at onFinish (_http_outgoing.js:792:10)
              at callback (internal/streams/writable.js:513:21)
              at afterWrite (internal/streams/writable.js:466:5)
              at afterWriteTick (internal/streams/writable.js:453:10)
              at processTicksAndRejections (internal/process/task_queues.js:81:21)
    }
    responseTime: 37
    req: {
      "id": 179,
      "method": "POST",
      "url": "/api/webhooks/schema/app_dev_06d58e316fc64a88a9a5955c2a298dcb/wh_5f258f7919ff48fbb1b8bcaeba41a5a9",
      "headers": {
        "connection": "upgrade",
        "x-real-ip": "172.18.0.8",
        "x-forwarded-for": "172.18.0.8",
        "host": "app-service:4002",
        "content-length": "442",
        "accept": "*/*",
        "content-type": "application/json",
        "x-signature": "XYZ*-******************************XYZ"
      },
      "remoteAddress": "::ffff:172.18.0.11",
      "remotePort": 55812
    }

```

Here is what the posted data looks like using a webhook test tool:

```
[
  {
    "id": "6242d0aa14274e175",
    "name": "Demo",
    "deleted": false,
    "description": "Toto",
    "createdAt": "2022-03-29 09:26:02",
    "modifiedAt": "2022-03-29 09:26:02",
    "demoStartDate": "2022-03-29",
    "demoEndDate": "2022-04-12",
    "isOngoingDemo": true,
    "createdById": "6230908bf4e0ab9f3",
    "assignedUserId": "6230909bf3e0ab9f3",
    "assignedUserName": "Toto",
    "teamsIds": [
      "6230a5be173e7a18e"
    ],
    "teamsNames": {
      "6230a5be173e7a18e": "Toto Team"
    },
    "leadId": "623e03f90e09cb54f",
    "leadName": "Mr Toto"
  }
]

```

initially teamsId and teamNames were showing empty arrays. But even with non-empty arrays, budibase still does an error 500.

It seems there is a null pointer occuring in /app/dist/api/controllers/webhook.js

**Comment by medvejonok79** [comment]
I think the problem may be that the CRM passes an array rather than a single value; this would need some kind of processing, worst case in some code ahead of budibase, if budibase can only handle one line at a time.

**Comment by Triloworld** [comment]
**Scenario case on cloud version:** 
- Add new webhook
- Use "Set Up Webhook" button
- Send empty POST message

**What should user see?**
Some information that empty POST was received.
If error/nulll data/some problem with query then debug screen must show what to align.

**What see?**
Nothing is visible on Budibase side. Error on side where POST come from

**Comment by melohagan** [comment]
I believe this is a duplicate of this issue:
- https://github.com/Budibase/budibase/issues/7360

Closing.
