### ISSUE TITLE
Public Apps no longer accessible

### ISSUE THREAD

**Issue by bmcbride** [Budibase/budibase#5158]
**Describe the bug**
I have an app with Public access, which has been working as expected until very recently. Currently on version 1.0.98, if I try accessing the app while logged out or in an Incognito window, I receive the following error:

```
{
message: "Missing/invalid DB name",
status: 500
}
```

I've confirmed all resources are set to Public access and I even tried building a super simple app with Public access, which results in the same error. Duplicating the same simple app in the Budibase cloud environment (on version 1.0.93), the Public access works as expected. I tried reverting back (to 1.0.73) and that did not solve the issue, so I'm stuck with an app that I cannot seem to make publicly accessible. Any insight or help you could provide would be really appreciated.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 99.0.4844.83

**Comment by Rory-Powell** [comment]
Thanks for reporting @bmcbride. Looking into this

**Comment by bmcbride** [comment]
Thanks @Rory-Powell! Let me know if you need anything else. We are in the middle of rolling out this form for public submission so this has got me a bit jammed up at the moment!

**Comment by Rory-Powell** [comment]
Hi @bmcbride. I haven't been able to reproduce this. How is your installation deployed? You might want to check that the `proxy-service` is up to date. Can you confirm the path portion of your url that is being used to access the app?

**Comment by Kuuchuu** [comment]
Only my most recently edited app before the update is accessible now. Any attempt to open a different published app redirects to the app edited before the update. Any way to downgrade? @Rory-Powell

**Comment by Kuuchuu** [comment]
My installation is deployed through Docker. I updated with docker-compose pull as I always have

**Comment by Kuuchuu** [comment]
I can now confirm that this is the same issue as OP's. I got the same error message when accessing the app from incognito:
```
{"message":"Missing/invalid DB name","status":500}
```

**Comment by Kuuchuu** [comment]
bbapps Log:
```
ERROR [1648574271821] (30 on d361e492cc19): Missing/invalid DB name
    Error: Missing/invalid DB name
        at PouchAlt.PouchDB (/app/node_modules/pouchdb/lib/index.js:2649:11)
        at new PouchAlt (/app/node_modules/pouchdb/lib/index.js:2786:13)
        at getDB (/app/node_modules/@budibase/backend-core/src/context/index.js:191:8)
        at exports.getAppDB (/app/node_modules/@budibase/backend-core/src/context/index.js:210:10)
        at /app/dist/api/controllers/static/index.js:72:20
        at Generator.next (<anonymous>)
        at /app/dist/api/controllers/static/index.js:8:71
        at new Promise (<anonymous>)
        at __awaiter (/app/dist/api/controllers/static/index.js:4:12)
        at exports.serveApp (/app/dist/api/controllers/static/index.js:70:12)
        at dispatch (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:44:32)
        at next (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:45:18)
        at /app/node_modules/@koa/router/lib/router.js:346:16
        at dispatch (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:44:32)
        at next (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:45:18)
        at allowedMethods (/app/node_modules/@koa/router/lib/router.js:407:12)
Trace: Error: Missing/invalid DB name
    at PouchAlt.PouchDB (/app/node_modules/pouchdb/lib/index.js:2649:11)
    at new PouchAlt (/app/node_modules/pouchdb/lib/index.js:2786:13)
    at getDB (/app/node_modules/@budibase/backend-core/src/context/index.js:191:8)
    at exports.getAppDB (/app/node_modules/@budibase/backend-core/src/context/index.js:210:10)
    at /app/dist/api/controllers/static/index.js:72:20
    at Generator.next (<anonymous>)
    at /app/dist/api/controllers/static/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/dist/api/controllers/static/index.js:4:12)
    at exports.serveApp (/app/dist/api/controllers/static/index.js:70:12)
    at dispatch (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:44:32)
    at next (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:45:18)
    at /app/node_modules/@koa/router/lib/router.js:346:16
    at dispatch (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:44:32)
    at next (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:45:18)
    at allowedMethods (/app/node_modules/@koa/router/lib/router.js:407:12)
    at /app/dist/api/index.js:67:21
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/api/index.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
INFO  [1648574271823] (30 on d361e492cc19): request errored
    res: {
      "statusCode": 500,
      "headers": {
        "vary": "Accept-Encoding",
        "content-type": "application/json; charset=utf-8",
        "content-length": "50"
      }
    }
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:77:38)
              at ServerResponse.emit (events.js:412:35)
              at ServerResponse.emit (domain.js:475:12)
              at ServerResponse.emitted (/app/node_modules/emitter-listener/listener.js:134:21)
              at onFinish (_http_outgoing.js:792:10)
              at callback (internal/streams/writable.js:513:21)
              at afterWrite (internal/streams/writable.js:466:5)
              at afterWriteTick (internal/streams/writable.js:453:10)
              at processTicksAndRejections (internal/process/task_queues.js:81:21)
    }
    responseTime: 6
    req: {
      "id": 1128,
      "method": "GET",
      "url": "/bowman",
      "headers": {
        "host": "brink.****.com",
        "x-forwarded-for": "192.168.1.1",
        "x-forwarded-host": "brink.****.com",
        "x-forwarded-proto": "https",
        "x-forwarded-ssl": "on",
        "x-real-ip": "192.168.1.1",
        "cache-control": "max-age=0",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36",
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "sec-gpc": "1",
        "sec-fetch-site": "same-origin",
        "sec-fetch-mode": "navigate",
        "sec-fetch-user": "?1",
        "sec-fetch-dest": "document",
        "referer": "https://brink.****.com/builder/portal/apps",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.9",
        "cookie": "budibase:auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c18yZDIzMTkxMzIyOWU0OThjYmE2ZjkzZTAzYjRhMjZhNyIsInNlc3Npb25JZCI6IjMyYTY5ZWNmYzEzYjQxMTM5ODkwZGJlODY3YmE1ODlkIiwidGVuYW50SWQiOiJkZWZhdWx0IiwiaWF0IjoxNjQ4NTc0MTE4fQ.TlHBzH9cUGcmVA8rLD1aRjk2nMm_GURIbi3CVyFqvsE; budibase:auth.sig=5OctydMzNbWQbHSBAahD1v-4TdM",
        "x-envoy-internal": "true",
        "x-request-id": "8a28b499-fce4-4b6e-81d3-0cdc9127ba24",
        "x-envoy-expected-rq-timeout-ms": "15000",
        "x-envoy-original-path": "/app/bowman",
        "content-length": "0"
      },
      "remoteAddress": "::ffff:172.31.0.7",
      "remotePort": 55046
    }
```

**Comment by bmcbride** [comment]
@Rory-Powell my installation is deployed via Docker as well. I'm experiencing the same behavior as @Kuuchuu with odd redirects when logged in, but the 500 error when logged out.

**Comment by Kuuchuu** [comment]
@bmcbride I was able to revert and get my setup working again. After reverting all the apps I upgraded I changed the tags on the docker images to the version I was on before (budibase.docker.scarf.sh/budibase/apps:v1.0.90, and budibase.docker.scarf.sh/budibase/worker:v1.0.90), then brought it down and back up. Seems to be okay at the moment.

**Comment by bmcbride** [comment]
Thanks for the update @Kuuchuu! So you went into the app, clicked the upgrade/reload button to get the App Version dialog, selected Revert (my option is to revert to 1.0.73), and then changed the tags on the docker images? Did you need to unpublish or republish the apps after bringing it back up?

**Comment by Kuuchuu** [comment]
@bmcbride Correct, that is the process I took. I did not need to unpublish or republish in my scenario.

**Comment by Rory-Powell** [comment]
@Kuuchuu thanks for including the logs, from what I can see on the `bbapps` log the request is hitting
`/bowman`. In the latest version this should be `/app/bowman` which leads me to believe your `budibase/proxy` image is behind. There has been a change to remove the url rewriting where we used to remove the `/app` prefix before sending to the apps container. Can you try running:
```
docker pull budibase/proxy
```

I've tried with a fresh installation and can't see any problems. You could also compare the created at times of the images with `docker ps` to see if the proxy image is behind. This might be the case for you as well @bmcbride

**Comment by Rory-Powell** [comment]
@Kuuchuu also noticed in your logs that you are still using envoy which would explain things here. We moved to nginx for a variety of reasons. 

To migrate to the latest infrastructure you can find the most recent `docker-compose.yaml` here:
https://github.com/Budibase/budibase/blob/master/hosting/docker-compose.yaml

Additionally you should place the `.env` file in the same directory as your compose file:
https://github.com/Budibase/budibase/blob/master/hosting/.env
This replaces `hosting.properties`. The properties should match, so you should be able to copy your existing properties over or even just rename the properties file to `.env`.

**Comment by Kuuchuu** [comment]
@Rory-Powell I am not using that image at all for my proxy in my Budibase stack.
When I initally set up Budibase the docker-compose.yml provided had this image as the proxy service:
```
  proxy-service:
    restart: always
    image: envoyproxy/envoy:v1.16-latest
    networks:
      - budibase
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "${MAIN_PORT}:10000"
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service
```

I can try to change over to the image you stated to see if that resolves the issue. It'll be a moment before I can do so though.

**Comment by bmcbride** [comment]
Migrating to the latest `docker-compose.yaml` seems to have solved the issue! Thanks for the help @Rory-Powell & @Kuuchuu. I'm up and running now but I'll wait for @Kuuchuu to reply and if he's all sorted out, we can probably close this ticket. I'm advocating hard for my organization to go all-in with BB, so got a little worried today, but top notch support from the community has me feeling much better. Keep up the awesome work!

**Comment by Rory-Powell** [comment]
For anyone else coming across this issue we have added the above steps as a migration guide
https://github.com/Budibase/budibase/discussions/5169

**Comment by Kuuchuu** [comment]
Sorry about the wait, had to wait on some locations to close for the day. The migration for me did not go smoothly. I am currently getting "502 Bad Gateway" upon attempting to load up the site. The new proxy container has this in its log:
```
192.168.1.254 - - [30/Mar/2022:14:42:55 +0000] "GET / HTTP/1.1" 502 552 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36"

2022/03/30 14:42:55 [error] 56#56: *54 app-service could not be resolved (3: Host not found), client: 192.168.1.254, server: _, request: "GET / HTTP/1.1", host: "brink.****.com"
```
@Rory-Powell

**Comment by lsoica** [comment]
This is still present when deploying BB in k8s with the helm chart form tag v1.0.112

Here are the logs from the app service POD:

```
ERROR [1649843376552] (29 on app-service-68c7d596b4-vxpkk): Missing/invalid DB name
    Error: Missing/invalid DB name
        at PouchAlt.PouchDB (/app/node_modules/pouchdb/lib/index.js:2649:11)
        at new PouchAlt (/app/node_modules/pouchdb/lib/index.js:2786:13)
        at getDB (/app/node_modules/@budibase/backend-core/src/context/index.js:191:8)
        at exports.getAppDB (/app/node_modules/@budibase/backend-core/src/context/index.js:210:10)
        at /app/dist/api/controllers/static/index.js:72:20
        at Generator.next (<anonymous>)
Trace: Error: Missing/invalid DB name
    at PouchAlt.PouchDB (/app/node_modules/pouchdb/lib/index.js:2649:11)
    at new PouchAlt (/app/node_modules/pouchdb/lib/index.js:2786:13)
    at getDB (/app/node_modules/@budibase/backend-core/src/context/index.js:191:8)
    at exports.getAppDB (/app/node_modules/@budibase/backend-core/src/context/index.js:210:10)
    at /app/dist/api/controllers/static/index.js:72:20
    at Generator.next (<anonymous>)
    at /app/dist/api/controllers/static/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/dist/api/controllers/static/index.js:4:12)
    at exports.serveApp (/app/dist/api/controllers/static/index.js:70:12)
    at dispatch (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:44:32)
    at next (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:45:18)
    at /app/node_modules/@koa/router/lib/router.js:346:16
    at dispatch (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:44:32)
    at next (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:45:18)
    at allowedMethods (/app/node_modules/@koa/router/lib/router.js:407:12)
    at /app/dist/api/index.js:67:21
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/api/index.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at /app/dist/api/controllers/static/index.js:8:71
        at new Promise (<anonymous>)
        at __awaiter (/app/dist/api/controllers/static/index.js:4:12)
        at exports.serveApp (/app/dist/api/controllers/static/index.js:70:12)
        at dispatch (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:44:32)
        at next (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:45:18)
        at /app/node_modules/@koa/router/lib/router.js:346:16
        at dispatch (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:44:32)
        at next (/app/node_modules/@koa/router/node_modules/koa-compose/index.js:45:18)
        at allowedMethods (/app/node_modules/@koa/router/lib/router.js:407:12)
INFO  [1649843376554] (29 on app-service-68c7d596b4-vxpkk): request errored
    res: {
      "statusCode": 500,
      "headers": {
        "vary": "Accept-Encoding",
        "content-type": "application/json; charset=utf-8",
        "content-length": "50"
      }
    }
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:77:38)
              at ServerResponse.emit (events.js:412:35)
              at ServerResponse.emit (domain.js:475:12)
              at ServerResponse.emitted (/app/node_modules/emitter-listener/listener.js:134:21)
              at onFinish (_http_outgoing.js:792:10)
              at callback (internal/streams/writable.js:513:21)
              at afterWrite (internal/streams/writable.js:466:5)
              at afterWriteTick (internal/streams/writable.js:453:10)
              at processTicksAndRejections (internal/process/task_queues.js:81:21)
    }
    responseTime: 24
    req: {
      "id": 45,
      "method": "GET",
      "url": "/app/bamboo",
      "headers": {
        "host": "apps.paas-2.0.nci.buc.ds.jdsu.net",
        "connection": "close",
        "x-request-id": "8aa2aadc95ae94ea59bc1fd71eb84ca7",
        "x-real-ip": "10.241.125.154",
        "x-forwarded-for": "10.241.125.154",
        "x-forwarded-host": "apps.paas-2.0.nci.buc.ds.jdsu.net",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
        "x-forwarded-scheme": "https",
        "x-scheme": "https",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.79 Safari/537.36",
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "sec-gpc": "1",
        "sec-fetch-site": "none",
        "sec-fetch-mode": "navigate",
        "sec-fetch-user": "?1",
        "sec-fetch-dest": "document",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-GB,en;q=0.9"
      },
      "remoteAddress": "::ffff:10.244.3.46",
      "remotePort": 38346
    }


```

**Comment by Rory-Powell** [comment]
@lsoica the request looks like it's using the correct routing so your proxy is up to date unlike the other cases above. 

The next most obvious issue here might be a mismatch in the production app url, can we check the app document before doing anything else to make sure things match up by looking at the network response for `api/applications?status=all` when viewing all apps. It should be `/bamboo` based on the log above. If this is the case we can dig deeper.

**Comment by lsoica** [comment]
@Rory-Powell here it is:
```
[
   {
      "_id":"app_metadata",
      "_rev":"270-99cc402c8e737e79bb139c5e8feb9622",
      "appId":"app_default_1fd47dbafd594e13bb7253d3a26aab55",
      "type":"app",
      "version":"1.0.103",
      "componentLibraries":[
         "@budibase/standard-components"
      ],
      "name":"NCI Portal",
      "url":"/nci",
      "instance":{
         "_id":"app_default_1fd47dbafd594e13bb7253d3a26aab55"
      },
      "tenantId":"default",
      "updatedAt":"2022-04-08T17:34:49.038Z",
      "createdAt":"2022-04-08T09:16:33.228Z",
      "status":"published"
   },
   {
      "_id":"app_metadata",
      "_rev":"680-8fc8f3e727cfcc37d1d92ba4164a5df9",
      "appId":"app_default_278d00cf9f22473d983ecde12035ca03",
      "type":"app",
      "version":"1.0.103",
      "componentLibraries":[
         "@budibase/standard-components"
      ],
      "name":"bamboo",
      "url":"/bamboo",
      "instance":{
         "_id":"app_default_278d00cf9f22473d983ecde12035ca03"
      },
      "tenantId":"default",
      "updatedAt":"2022-04-13T09:12:48.707Z",
      "createdAt":"2022-04-01T08:33:44.153Z",
      "status":"published",
      "theme":"spectrum--light",
      "customTheme":{
         "navBackground":"var(--spectrum-global-color-gray-50)",
         "buttonBorderRadius":"4px"
      }
   },
   {
      "_id":"app_metadata",
      "_rev":"269-1ef31285a77cbeea9f7fe40d026c21bb",
      "appId":"app_dev_default_1fd47dbafd594e13bb7253d3a26aab55",
      "type":"app",
      "version":"1.0.103",
      "componentLibraries":[
         "@budibase/standard-components"
      ],
      "name":"NCI Portal",
      "url":"/nci",
      "instance":{
         "_id":"app_dev_default_1fd47dbafd594e13bb7253d3a26aab55"
      },
      "tenantId":"default",
      "updatedAt":"2022-04-08T17:35:23.021Z",
      "createdAt":"2022-04-08T09:16:33.228Z",
      "status":"development"
   },
   {
      "_id":"app_metadata",
      "_rev":"679-78a5c406800030b3fa51c991cdeabc59",
      "appId":"app_dev_default_278d00cf9f22473d983ecde12035ca03",
      "type":"app",
      "version":"1.0.103",
      "componentLibraries":[
         "@budibase/standard-components"
      ],
      "name":"bamboo",
      "url":"/bamboo",
      "instance":{
         "_id":"app_dev_default_278d00cf9f22473d983ecde12035ca03"
      },
      "tenantId":"default",
      "updatedAt":"2022-04-13T09:12:48.707Z",
      "createdAt":"2022-04-01T08:33:44.153Z",
      "status":"development",
      "theme":"spectrum--light",
      "customTheme":{
         "navBackground":"var(--spectrum-global-color-gray-50)",
         "buttonBorderRadius":"4px"
      }
   }
]
```

**Comment by Rory-Powell** [comment]
@lsoica can you check if visiting the app directly works: 
https://your.hostname/app_default_278d00cf9f22473d983ecde12035ca03

**Comment by lsoica** [comment]
@Rory-Powell ,yes, it works.

**Comment by Rory-Powell** [comment]
Thanks that narrows down things a lot. The problem seems to be around detecting the correct tenant id, when authenticated this will come from the session. When visiting a public app as an unauthenticated user this will be derived from the incoming request. Given that you are using a single tenant environment this shouldn't be an issue, the only thing that looks like it could be getting in the way is a check on the the self hosted flag which will try to derive the tenant id from the url in our cloud installation. 

Just to check, could you run this command and ensure the value of your `SELF_HOSTED` flag is `1`
```
kubectl exec -it app-service-68c7d596b4-vxpkk -- env
```

**Comment by lsoica** [comment]
```
$ kubectl exec -it -n budibase app-service-68c7d596b4-vxpkk -- env|grep SELF_HOSTED
SELF_HOSTED=1
```
