### ISSUE TITLE
formula column anomaly

### ISSUE THREAD

**Issue by marco-santulli** [Budibase/budibase#5761]
I have a postgres DB and am on latest 145 release.

I created a simple formula column, added it to a design, everything worked as expected. 

I then tried to rename the column, I have received an error, but from that point on, in budi I see the old name in the table and the new name when I click on edit the column:
see column name test1:
![image](https://user-images.githubusercontent.com/82715690/167252899-d2f120be-1cfd-4b5b-ac75-43efb8bb8f19.png)

but in the edit column:
![image](https://user-images.githubusercontent.com/82715690/167252971-10fdad7f-2a71-4ae3-a99d-d51fba64c06a.png)

it is test2.

If I try to rename it or delete it I get no error in the GUI, but in the logs I see:
ERROR [1651923653713] (30 on 5b3eb0f6d3dd): error: column "test1" does not exist
    Error: error: column "test1" does not exist
        at PostgresIntegration.<anonymous> (/app/dist/integrations/postgres.js:141:27)
        at Generator.throw (<anonymous>)
        at rejected (/app/dist/integrations/postgres.js:6:65)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
Trace: Error: error: column "test1" does not exist
    at PostgresIntegration.<anonymous> (/app/dist/integrations/postgres.js:141:27)
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/integrations/postgres.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /app/dist/api/index.js:72:21
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/api/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
INFO  [1651923653716] (30 on 5b3eb0f6d3dd): request errored
    res: {
      "statusCode": 500,
      "headers": {
        "vary": "Accept-Encoding",
        "content-type": "application/json; charset=utf-8",
        "content-length": "65"
      }
    }
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:77:38)
              at ServerResponse.emit (events.js:412:35)
              at ServerResponse.emit (domain.js:475:12)
              at ServerResponse.emitted (/app/node_modules/emitter-listener/listener.js:134:21)
              at onFinish (_http_outgoing.js:792:10)
              at callback (internal/streams/writable.js:513:21)
              at afterWrite (internal/streams/writable.js:466:5)
              at afterWriteTick (internal/streams/writable.js:453:10)
              at processTicksAndRejections (internal/process/task_queues.js:81:21)
    }
    responseTime: 159
    req: {
      "id": 54,

**Comment by JeroenvdBurg** [comment]
Having exact the same thing. I tried some other connectors. In MySql it still works to rename a formula column, deleting however is not working. In Postgres en MsSQL it is both broken.  Tried to debug it but till now I couldn't find it. 

Could someone help on resolving this ?

**Comment by JeroenvdBurg** [comment]
@mike12345567 any thoughts on this one?

**Comment by melohagan** [comment]
Should be fixed with this PR: https://github.com/Budibase/budibase/pull/7574
Duplicate of: https://github.com/Budibase/budibase/issues/5733

Closing.
