### ISSUE TITLE
Trouble linking google sheets

### ISSUE THREAD

**Issue by lanmower** [Budibase/budibase#6005]
### Discussed in https://github.com/Budibase/budibase/discussions/6004

<div type='discussions-op-text'>

<sup>Originally posted by **lanmower** May 20, 2022</sup>
![image](https://user-images.githubusercontent.com/657315/169547638-08f600f4-a151-4c9e-ac97-32501434fedf.png)

bbapps log

```Error connecting to google sheets Error: Error authenticating with google sheets.
    at GoogleSheetsIntegration.<anonymous> (/app/dist/integrations/googlesheets.js:134:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/integrations/googlesheets.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR [1653056395788] (30 on 066eadeb0b1d): Error authenticating with google sheets.
    Error: Error authenticating with google sheets.
        at GoogleSheetsIntegration.<anonymous> (/app/dist/integrations/googlesheets.js:134:27)
        at Generator.next (<anonymous>)
        at fulfilled (/app/dist/integrations/googlesheets.js:5:58)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
Trace: Error: Error authenticating with google sheets.
    at GoogleSheetsIntegration.<anonymous> (/app/dist/integrations/googlesheets.js:134:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/integrations/googlesheets.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /app/dist/api/index.js:72:21
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/api/index.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
INFO  [1653056395807] (30 on 066eadeb0b1d): request errored
    res: {
      "statusCode": 500,
      "headers": {
        "vary": "Accept-Encoding",
        "content-type": "application/json; charset=utf-8",
        "content-length": "67"
      }
    }
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:77:38)
              at ServerResponse.emit (events.js:412:35)
              at ServerResponse.emit (domain.js:475:12)
              at onFinish (_http_outgoing.js:792:10)
              at callback (internal/streams/writable.js:513:21)
              at afterWrite (internal/streams/writable.js:466:5)
              at afterWriteTick (internal/streams/writable.js:453:10)
              at processTicksAndRejections (internal/process/task_queues.js:81:21)
    }
    responseTime: 553
    req: {
      "id": 950,
      "method": "POST",
      "url": "/api/datasources/datasource_plus_3ea54dc0056a470db17b66efa2eb8eee/schema",
      "headers": {
        "connection": "upgrade",
        "x-real-ip": "172.18.0.1",
        "x-forwarded-for": "172.18.0.1",
        "host": "app-service:4002",
        "content-length": "0",
        "cookie": "csrftoken=ALcx5Invz9jgRb5m9yM98VRTVpR9HkqO; showAllAp=true; budibase:init=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTMwNTI1MzZ9.pwiVhh0NMcYCrX6eRTDjkQuy0b0do9NZODT1XWyPlco; budibase:init.sig=qXzXwxDMgFsW0enVFMsNhGUPPrA; budibase:auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c182NjQ5ZWM0ZmExNWY0MGFhYWVmMDc5ZDNmNzMyZDlhMyIsInNlc3Npb25JZCI6IjhmMTE3ZGE4ZmRiYTQ5OWVhZWM2YzExN2NjYWJiZWI5IiwidGVuYW50SWQiOiJkZWZhdWx0IiwiaWF0IjoxNjUzMDU1ODMzfQ.uGsKtMTZxo2U9iM45OS_469nG-wJMjr2PjqRHjNcp6A; budibase:auth.sig=l1Q21ouyxvraZMUMtkkg7-PRM7o; budibase:currentapp=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImFwcF9kZXZfOTMwMWY5MzAyNTI1NDYyZWIyNTIwYzA3YmQxNDc0NTYiLCJpYXQiOjE2NTMwNTU5MjZ9.3g4L2AY1QKDOpiudx70Nr7X8466baGcnhTY3m7VpEjU",
        "accept-language": "en-US,en;q=0.9",
        "accept-encoding": "gzip, deflate, br",
        "referer": "https://sheppie.myqnapcloud.com/builder/app/app_dev_9301f9302525462eb2520c07bd147456/data/datasource/datasource_plus_3ea54dc0056a470db17b66efa2eb8eee",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "origin": "https://sheppie.myqnapcloud.com",
        "sec-ch-ua-platform": "\"Windows\"",
        "accept": "application/json",
        "content-type": "application/json",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36",
        "sec-ch-ua-mobile": "?0",
        "x-budibase-api-version": "1",
        "x-csrf-token": "ccbcea2a-dd9b-40c3-8d64-df98981c8628",
        "x-budibase-app-id": "app_dev_9301f9302525462eb2520c07bd147456",
        "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"101\", \"Google Chrome\";v=\"101\""
      },
      "remoteAddress": "::ffff:172.18.0.6",
      "remotePort": 44724
    }
```

Google console verified, api library verified spreadsheets is enabled, used oauth web app type.

in browser log

![image](https://user-images.githubusercontent.com/657315/169548284-ce7fa349-9c2d-49b2-a8ae-8a75e17eeaaf.png)

The oauth flow has no errors, I can see its asking for spreadsheet access, and it accepts, I can also log into the app with my user.</div>

**Comment by shogunpurple** [comment]
This should now be fixed - closing

**Comment by JeroenvdBurg** [comment]
Not sure in which branch this is fixed, however when I checkout the current master branch and succesfully link my google account with the oauth flow I still get an error when fetching tables from a spreadsheet.

I have included clientID and clientSecret in docker-compose file.

![image](https://user-images.githubusercontent.com/30255073/173179879-df257fdc-9e27-446c-859f-c2602dac769b.png)
