### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by marco-santulli** [Budibase/budibase#6438]
Hi,

just migrated an app from an old version (105) to the latest (206), an application seems to have a problem on the database connector, looking at the log we get this error (but the table is there and the column is there).  
ERROR [1655938238439] (30 on a2a17b568ef3): error: column "UltimoDurc" of relation "fornitori" does not exist
    Error: error: column "UltimoDurc" of relation "fornitori" does not exist
        at PostgresIntegration.<anonymous> (/app/dist/integrations/postgres.js:175:27)
        at Generator.next (<anonymous>)
        at fulfilled (/app/dist/integrations/postgres.js:5:58)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
Trace: Error: error: column "UltimoDurc" of relation "fornitori" does not exist
    at PostgresIntegration.<anonymous> (/app/dist/integrations/postgres.js:175:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/integrations/postgres.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /app/dist/api/index.js:72:17
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/

 The strange thing is that going into the "data" area the table seems to be empty but it is not.

![image](https://user-images.githubusercontent.com/82715690/175169998-e9cb8d69-d2ac-4359-abaa-cbe93eca9518.png)

**Comment by marchellodev** [comment]
In my case, the problem arises since in my database I have records like `0000-00-00 00:00:00.000` in the `datetime(3)` column. As soon as I remove all those records, the database is displayed fine again

**Comment by marchellodev** [comment]
Is it maybe possible to downgrade budibase to the prev version? @marco-santulli @shogunpurple @pueding @panos-- 

I do not mean a budibase project, but the whole system.
