### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:4001

### ISSUE THREAD

**Issue by zhengtulymGh** [Budibase/budibase#6543]
branch: master

It seems to be staring “server” server failed
```
ERROR [1656932806911] (62979 on liyimin.local): request to http://localhost:4001/api/users/metadata/sync/us_6811971f545b4098a7a70cc9f69c75a1 failed, reason: connect ECONNREFUSED 127.0.0.1:4001
@budibase/worker:     message: "request to http://localhost:4001/api/users/metadata/sync/us_6811971f545b4098a7a70cc9f69c75a1 failed, reason: connect ECONNREFUSED 127.0.0.1:4001"
@budibase/worker:     type: "system"
@budibase/worker:     errno: "ECONNREFUSED"
@budibase/worker:     code: "ECONNREFUSED"
@budibase/worker:     expose: true
@budibase/worker:     statusCode: 400
@budibase/worker:     status: 400
@budibase/worker:     stack: "FetchError: request to http://localhost:4001/api/users/metadata/sync/us_6811971f545b4098a7a70cc9f69c75a1 failed, reason: connect ECONNREFUSED 127.0.0.1:4001\n    at ClientRequest.<anonymous> (/Users/11097243/Documents/tem/LowerCode/budibase-master/packages/worker/node_modules/node-fetch/lib/index.js:1491:11)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at Socket.socketErrorListener (_http_client.js:475:9)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
@budibase/worker:     req: {
@budibase/worker:       "id": 7,
@budibase/worker:       "method": "POST",
@budibase/worker:       "url": "/api/global/users/init",
@budibase/worker:       "headers": {
@budibase/worker:         "host": "localhost.vmic.xyz",
@budibase/worker:         "connection": "close",
@budibase/worker:         "content-length": "61",
@budibase/worker:         "accept": "application/json",
@budibase/worker:         "x-budibase-app-id": "",
@budibase/worker:         "x-csrf-token": "ded5429d-4704-46c0-ba90-bd021656e588",
@budibase/worker:         "x-budibase-api-version": "1",
@budibase/worker:         "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
@budibase/worker:         "content-type": "application/json",
@budibase/worker:         "origin": "http://localhost.vmic.xyz:10000",
@budibase/worker:         "referer": "http://localhost.vmic.xyz:10000/builder/admin",
@budibase/worker:         "accept-encoding": "gzip, deflate",
@budibase/worker:         "accept-language": "zh-CN,zh;q=0.9",
@budibase/worker:         "cookie": "budibase:init=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTY1NzYwMjZ9.wf7YyW0nGDEnim2GfWYVslcfvrtEu4se33K50X1bIaA; budibase:init.sig=4IwpG3Sj2LEkIcAavI16V3Q_Byw; CSRF_TOKEN=YjNjMjM2ODQyZjJkYzI2OWQ0ZWYwOWM2MDc4YzdmNDQ=; token=\"PbVaR_W52nlKRy6.5uZIc.BtqIdzSiuoFNC6IvH3DJRkPWD9SNsFkJ4r_GbJVcIiak70TI2F9tU*\"; budibase:auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c19lN2Q5ZmUyMTRkOTQ0Yjg0OGI5ZDg3NDFjMDkwYjdmMCIsInNlc3Npb25JZCI6ImZlNDA2NjcxMjk0ZjQ4OTliN2QzOTFkZmFiMmE2NTkwIiwidGVuYW50SWQiOiJkZWZhdWx0IiwiaWF0IjoxNjU2OTI0OTk3fQ.0zEy_G8Dka1DbGsIDMww_fdNcvZJL-Yln1Y6BmUVmoU; budibase:auth.sig=FTZ1ROyFEeuxfJ43vQJHWT8R0Q0"
@budibase/worker:       },
@budibase/worker:       "remoteAddress": "::ffff:127.0.0.1",
@budibase/worker:       "remotePort": 52371
@budibase/worker:     }
```

**Comment by mike12345567** [comment]
Hi @zhengtulymGh - we could do with a few more details to help work out this issue, such as:
1. Are you trying to run Budibase in development, from the master branch
2. If running from development, could you include some info about your system, e.g. operating system, version of Node, are you using NPM, Yarn, PNPM etc
3. What method you used to start the system e.g. did you follow the steps in our [contributing guide](https://github.com/Budibase/budibase/blob/develop/docs/CONTRIBUTING.md).

**Comment by zhengtulymGh** [comment]
Yes，I'm sure I run Budibase in development.
Is it caused by this error？
```
Budibase running on {"address":"::","family":"IPv6","port":4001}
@budibase/server: Redis Client Error [ErrorReply: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?]
@budibase/server: [WARN] This Redis server's `default` user does not require a password, but a password was supplied
@budibase/server: [WARN] This Redis server's `default` user does not require a password, but a password was supplied
@budibase/server: Redis Client Error [ErrorReply: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?]
@budibase/server: Redis Client Error [ErrorReply: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?]
@budibase/server: Redis Client Error [ErrorReply: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?]
@budibase/server: Redis Client Error [ErrorReply: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?]
@budibase/server: Checking migrations
@budibase/server: [WARN] This Redis server's `default` user does not require a password, but a password was supplied
@budibase/server: Redis Client Error [ErrorReply: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?]
```

**Comment by mike12345567** [comment]
Hi @zhengtulymGh that error does look like something is incorrect, but as I said in the previous comment, we will need more details about your setup to be able to help.

**Comment by zhengtulymGh** [comment]
operating system: macOS Monterey(version 12.2.1)
node verion: v14.19.0

I using yarn
yarn version: 1.22.18

And I have follow the steps in our contributing guide

**Comment by zhengtulymGh** [comment]
Hi @mike12345567 , the cpu of my mac is Intel Core i9, not ARM-based.
Here are my ```.env`` configs that I think have been configured fully.

```packages/server/.env```
```
PORT=4001
MINIO_URL=http://localhost:4004
COUCH_DB_URL=http://budibase:budibase@localhost:4005
REDIS_URL=localhost:6379
WORKER_URL=http://localhost:4002
INTERNAL_API_KEY=budibase
ACCOUNT_PORTAL_URL=http://localhost:10001
ACCOUNT_PORTAL_API_KEY=budibase
JWT_SECRET=testsecret
REDIS_PASSWORD=budibase
MINIO_ACCESS_KEY=budibase
MINIO_SECRET_KEY=budibase
COUCH_DB_PASSWORD=budibase
COUCH_DB_USER=budibase
SELF_HOSTED=1
DISABLE_ACCOUNT_PORTAL=
MULTI_TENANCY=
DISABLE_THREADING=1
SERVICE=app-service
DEPLOYMENT_ENVIRONMENT=development
```

```
packages/worker/.env
```
SELF_HOSTED=1
PORT=4002
CLUSTER_PORT=10000
JWT_SECRET=testsecret
INTERNAL_API_KEY=budibase
MINIO_ACCESS_KEY=budibase
MINIO_SECRET_KEY=budibase
REDIS_URL=localhost:6379
REDIS_PASSWORD=budibase
MINIO_URL=http://localhost:4004
COUCH_DB_URL=http://budibase:budibase@localhost:4005
COUCH_DB_USERNAME=budibase
COUCH_DB_PASSWORD=budibase
MULTI_TENANCY=
DISABLE_ACCOUNT_PORTAL=
ACCOUNT_PORTAL_URL=http://localhost:10001
ACCOUNT_PORTAL_API_KEY=budibase
PLATFORM_URL=http://localhost:10000
APPS_URL=http://localhost:4001
SERVICE=worker-service
DEPLOYMENT_ENVIRONMENT=development

```

**Comment by zhengtulymGh** [comment]
Hi @mike12345567 , I have execute the following steps：
1、Stop and remove historical docker services: ```docker-compose  -f docker-compose.dev.yaml stop && docker-compose rm```
2、Clean  historical data: ```yarn nuke:docker```
3、Update docker to the latest, version is 4.10.1 (82475)
4、Update  master branch and it is up to date with 'origin/master'
5、Start width ```yarn setup && yarn dev```
However, the error still occurs:
```
@budibase/server: Redis Client Error [ErrorReply: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?]
@budibase/server: Checking migrations
@budibase/server: [WARN] This Redis server's `default` user does not require a password, but a password was supplied
@budibase/server: [Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Running 
@budibase/server: Redis Client Error [ErrorReply: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?]
@budibase/server: [Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Complete
@budibase/server: [Tenant: default] [Migration: quotas_1] [DB: global-db] Running 
@budibase/server: [Tenant: default] Syncing app count: 0
@budibase/server: [Tenant: default] [Migration: quotas_1] [DB: global-db] Error:  {
@budibase/server:   error: 'not_found',
@budibase/server:   reason: 'missing',
@budibase/server:   status: 404,
@budibase/server:   name: 'not_found',
@budibase/server:   message: 'missing',
@budibase/server:   stack: 'Error: \n' +
@budibase/server:     '    at generateErrorFromResponse (/Users/11097243/Documents/tem/LowerCode/budibase/packages/backend-core/node_modules/pouchdb/lib/index.js:694:18)\n' +
@budibase/server:     '    at /Users/11097243/Documents/tem/LowerCode/budibase/packages/backend-core/node_modules/pouchdb/lib/index.js:6816:19\n' +
@budibase/server:     '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
@budibase/server:   docId: 'usage_quota'
@budibase/server: }
@budibase/server: bb-alert: Error performing migrations. Exiting. : {"error":"not_found","reason":"missing","status":404,"name":"not_found","message":"missing","stack":"Error: \n    at generateErrorFromResponse (/Users/11097243/Documents/tem/LowerCode/budibase/packages/backend-core/node_modules/pouchdb/lib/index.js:694:18)\n    at /Users/11097243/Documents/tem/LowerCode/budibase/packages/backend-core/node_modules/pouchdb/lib/index.js:6816:19\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","docId":"usage_quota"}
@budibase/server: Server Closed
@budibase/server: [nodemon] clean exit - waiting for changes before restart
```

**Comment by Chukwu3meka** [comment]
@zhengtulymGh @mike12345567

You don't seem to have docker-compose installed. Try and run this command:

`sudo dnf -y install docker-compose`

**Comment by Chukwu3meka** [comment]
To solve the other error, you mentioned

> [WARN] This Redis server's `default` user does not require a password, but a password was supplied
@budibase/server: 

To resolve <AUTH password:

1. `sudo systemctl start redis`
2. `sudo systemctl status redis` # make sure its running
3. `sudo nano /etc/redis/redis.conf`
4. Once nano opens the config file 'ctrl + w' to search
5. Then enter '# requirepass'
6. Now remove the pound sign before "'# requirepass ...'" to "requirepass ...'"
7. Update the text (password) after "'requirepass ... '" i.e whatever you have inplace of the ellipsis, change it to "budibase" 
    > "requirepass budibase"
8. `redis.cli`
9.  `CONFIG SET requirepass "budibase"`
10. `AUTH budibase`

After that, retry `yarn setup` && `yarn dev`

**Comment by Chukwu3meka** [comment]
You can checkout this [article](https://chukwu3meka.medium.com/budibase-dev-environment-setup-3685b5c1e771)

**Comment by zhengtulymGh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，来件已收到，我会尽快回复您。。。。
