### ISSUE TITLE
Unauthorized - no public worker access

### ISSUE THREAD

**Issue by matt0x6F** [Budibase/budibase#7425]
**Hosting**

- Self
  - Method: Docker Compose 
  - Budibase Version: 1.2.36

**Describe the bug**
I'm seeing the logs below in the server. My domain is served on a mesh and traffic is proxied through traefik and then to containers. I'm not quite sure what this error means nor how it received the domain configuration. This isn't something I gave to the worker as far as I know.

I did see this: https://github.com/Budibase/budibase/blob/master/packages/worker/src/environment.js#L43

Would it be relevant to set this to the internal address/name?

**To Reproduce**
1. Install budibase in Docker Compose
2. docker-compose up -d
3. Proxy traffic through traefik

**Expected behavior**

**Screenshots**

**Additional context**
Logs from worker:

```
ERROR [1661108438945] (29 on 392b97e5667d):
    req: {
      "id": 74,
      "method": "GET",
      "url": "/api/global/self",
      "headers": {
        "host": "budibase.<my domain>",
        "connection": "close",
        "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0",
        "accept": "application/json",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "cookie": "budibase:currentapp=<redacted>; budibase:returnurl=/app/brewdb",
        "dnt": "1",
        "referer": "https://budibase.<my domain>/builder/invite?code=<redacted>",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "sec-gpc": "1",
        "x-budibase-api-version": "1",
        "x-budibase-app-id": "",
        "x-forwarded-for": "172.21.0.1", # docker network address
        "x-forwarded-host": "budibase.<my domain>",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
        "x-forwarded-server": "08eb17a428c1",
        "x-real-ip": "172.21.0.1" # docker network address
      },
      "remoteAddress": "::ffff:172.23.0.9", # docker network address
      "remotePort": 47302 # local port
    }
    err: {
      "type": "ForbiddenError",
      "message": "Unauthorized - no public worker access",
      "stack":
          ForbiddenError: Unauthorized - no public worker access
              at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
              at /app/dist/api/index.js:110:18
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@koa/router/lib/router.js:368:16
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@budibase/pro/dist/index.js:1:9761
              at Generator.next (<anonymous>)
              at /app/node_modules/@budibase/pro/dist/index.js:1:3387
              at new Promise (<anonymous>)
              at Q (/app/node_modules/@budibase/pro/dist/index.js:1:3132)
              at /app/node_modules/@budibase/pro/dist/index.js:1:9557
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@koa/router/lib/router.js:368:16
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@budibase/backend-core/dist/src/middleware/csrf.js:51:20
              at Generator.next (<anonymous>)
      "status": 403,
      "statusCode": 403,
      "expose": true
    }
```

**Comment by aptkingston** [comment]
Hey @matt0x6F. Is this causing you any issues or are you just concerned that you're seeing this in the logs? This is perfectly normal, and would be logged if you tried to access Budibase while not logged in, for example. It's nothing to worry about. Were there any actual issues you were experiencing?

**Comment by matt0x6F** [comment]
Interesting! I did some reconfiguration of my networking last night and it went away. Sorry for the erroneous issue!
