### ISSUE TITLE
Error running budibase on linux: libvips-cpp.so.42: cannot open shared object file

### ISSUE THREAD

**Issue by opensas** [Budibase/budibase#770]
I downloaded the Budibase-Builder-0.2.5.AppImage

When I try to run it I get the following error:

```
$ ./Budibase-Builder-0.2.5.AppImage 
(node:4280) UnhandledPromiseRejectionWarning: Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/tmp/.mount_BudibaAsHVL3/resources/app.asar/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_BudibaAsHVL3/resources/app.asar/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
(node:4280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

some more info:

```
$ uname -a
Linux xps 5.0.0-1070-oem-osp1 #76-Ubuntu SMP Thu Oct 15 14:25:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
sas@xps:~/tmp/budibase
$ node -v
v12.11.1
sas@xps:~/tmp/budibase
$ npm -v
6.14.8
sas@xp
```

**Comment by shogunpurple** [comment]
Hi @opensas! Thanks for taking the time to write up this issue.

This is a problem with the `sharp` module not building properly on linux machines - we have run into it ourselves. We are currently in the process of switching sharp out for another module, which should resolve this problem. The release containing that fix should be out today.

**Comment by opensas** [comment]
wow, that's a quick reply indeed! I'll give it another try tomorrow, thanks a lot

**Comment by aptkingston** [comment]
Resolved as of https://github.com/Budibase/budibase/pull/774 👍  we'll hopefully get a release out soon with this included!

**Comment by shogunpurple** [comment]
This should be resolved in the latest release @opensas 👍
