### ISSUE TITLE
Error loading apps and templates

### ISSUE THREAD

**Issue by davidpfahler** [Budibase/budibase#8193]
**Hosting**
- Self
  - Method: docker-compose
  - Budibase Version: latest

**Describe the bug**
![Screen Shot 2022-10-10 at 10 48 59](https://user-images.githubusercontent.com/908242/194830707-5a4b9e5f-c6b3-43b9-9ac5-b701152bee72.png)

**To Reproduce**
1. Run docker-compose setup
2. Login
3. Go to Apps screen
  
**Desktop (please complete the following information):**
 - OS: macos 12.6
 - Browser Brave
 - Version v1.44.108

**Additional context**
Here are the logs from `docker-compose logs`:

```
bbapps                | ERROR [1665392082007] (30 on ddf74bb4abbe): ERR wrong number of arguments for 'mget' command
bbapps                |     ReplyError: ERR wrong number of arguments for 'mget' command
bbapps                |         at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
bbapps                |         at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
bbapps                | Trace: ReplyError: ERR wrong number of arguments for 'mget' command
bbapps                |     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
bbapps                |     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
bbapps                |   command: { name: 'mget', args: [] }
bbapps                | }
bbapps                |     at /app/dist/api/index.js:74:21
bbapps                |     at Generator.throw (<anonymous>)
bbapps                |     at rejected (/app/dist/api/index.js:6:65)
bbapps                |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
bbproxy               | 172.18.0.11 - - [10/Oct/2022:08:54:42 +0000] "GET /api/applications?status=all HTTP/1.1" 500 75 "https://apps.stegerpfahler.de/builder/portal/apps" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "77.2.49.53" response_time=0.063 proxy_host=app-service:4002 upstream_addr=172.18.0.9:4002
bbapps                | INFO  [1665392082022] (30 on ddf74bb4abbe): request errored
bbapps                |     res: {
bbapps                |       "statusCode": 500,
bbapps                |       "headers": {
bbapps                |         "vary": "Accept-Encoding",
bbapps                |         "content-type": "application/json; charset=utf-8",
bbapps                |         "content-length": "75"
bbapps                |       }
bbapps                |     }
bbapps                |     err: {
bbapps                |       "type": "Error",
bbapps                |       "message": "failed with status code 500",
bbapps                |       "stack":
bbapps                |           Error: failed with status code 500
bbapps                |               at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:77:38)
bbapps                |               at ServerResponse.emit (events.js:412:35)
bbapps                |               at ServerResponse.emit (domain.js:475:12)
bbapps                |               at onFinish (_http_outgoing.js:792:10)
bbapps                |               at callback (internal/streams/writable.js:513:21)
bbapps                |               at afterWrite (internal/streams/writable.js:466:5)
bbapps                |               at afterWriteTick (internal/streams/writable.js:453:10)
bbapps                |               at processTicksAndRejections (internal/process/task_queues.js:81:21)
bbapps                |     }
bbapps                |     responseTime: 61
bbapps                |     req: {
bbapps                |       "id": 21,
bbapps                |       "method": "GET",
bbapps                |       "url": "/api/applications?status=all",
bbapps                |       "headers": {
bbapps                |         "connection": "upgrade",
bbapps                |         "x-real-ip": "172.18.0.11",
bbapps                |         "x-forwarded-for": "77.2.49.53, 172.18.0.11",
bbapps                |         "host": "app-service:4002",
bbapps                |         "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
bbapps                |         "accept": "application/json",
bbapps                |         "accept-encoding": "gzip, deflate, br",
bbapps                |         "accept-language": "en-US,en;q=0.9,de;q=0.8",
bbapps                |         "cookie": "budibase:init=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjUzOTIwMDV9.WqmwbjHiLp4ud5_XV83EPpqb4rm6mSiS_-DwoZPD5ug; budibase:init.sig=NdY59ZBecLDWljEoYqtMi8hJlbo; budibase:auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c18xY2MzOWU5ZWE1NDE0ZjM5YTYwZWNjNmUyYmE4MzRmYyIsInNlc3Npb25JZCI6IjMyYTkxNDU0Nzg5MjRiM2Y5MGI3YjY4MDg0ZTVhMzZjIiwidGVuYW50SWQiOiJkZWZhdWx0IiwiaWF0IjoxNjY1MzkyMDIwfQ.bMG8q7WSAqTivEI-PHQgVVYjSdQXMPrHu43ngZ9Hz6Q; budibase:auth.sig=2glQ9XQ8RUC-5Tq4yxrBOa9aVz8; ph_phc_bIjZL7oh2GEUd2vqvTBH8WvrX0fWTFQMs6H5KQxiUxU_posthog=%7B%22distinct_id%22%3A%20%22us_1cc39e9ea5414f39a60ecc6e2ba834fc%22%2C%22%24device_id%22%3A%20%22183b301eb72122f-0a9c4909c701e3-19525635-16a7f0-183b301eb731687%22%2C%22%24user_id%22%3A%20%22us_1cc39e9ea5414f39a60ecc6e2ba834fc%22%2C%22%24initial_referrer%22%3A%20%22https%3A%2F%2Fapps.stegerpfahler.de%2Fbuilder%2Fauth%2Flogin%22%2C%22%24initial_referring_domain%22%3A%20%22apps.stegerpfahler.de%22%2C%22%24active_feature_flags%22%3A%20%5B%5D%7D",
bbapps                |         "referer": "https://apps.stegerpfahler.de/builder/portal/apps",
bbapps                |         "sec-fetch-dest": "empty",
bbapps                |         "sec-fetch-mode": "cors",
bbapps                |         "sec-fetch-site": "same-origin",
bbapps                |         "sec-gpc": "1",
bbapps                |         "x-budibase-api-version": "1",
bbapps                |         "x-budibase-app-id": "",
bbapps                |         "x-csrf-token": "afb93cd6-6953-4bce-be14-dc5724b30d60",
bbapps                |         "x-forwarded-proto": "https"
bbapps                |       },
bbapps                |       "remoteAddress": "::ffff:172.18.0.10",
bbapps                |       "remotePort": 44980
bbapps                |     }
bbapps                | INFO  [1665392082031] (30 on ddf74bb4abbe): request completed
bbapps                |     res: {
bbapps                |       "statusCode": 200,
bbapps                |       "headers": {
bbapps                |         "vary": "Accept-Encoding",
bbapps                |         "content-length": "6835",
bbapps                |         "last-modified": "Fri, 07 Oct 2022 17:23:06 GMT",
bbapps                |         "cache-control": "max-age=0",
bbapps                |         "content-type": "image/png"
bbapps                |       }
bbapps                |     }
bbapps                |     responseTime: 57
bbapps                |     req: {
bbapps                |       "id": 22,
bbapps                |       "method": "GET",
bbapps                |       "url": "/builder/assets/favicon.e7fc7733.png",
bbapps                |       "headers": {
bbapps                |         "connection": "upgrade",
bbapps                |         "x-real-ip": "172.18.0.11",
bbapps                |         "x-forwarded-for": "77.2.49.53, 172.18.0.11",
bbapps                |         "host": "app-service:4002",
bbapps                |         "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
bbapps                |         "accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
bbapps                |         "accept-encoding": "gzip, deflate, br",
bbapps                |         "accept-language": "en-US,en;q=0.9,de;q=0.8",
bbapps                |         "cookie": "budibase:init=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjUzOTIwMDV9.WqmwbjHiLp4ud5_XV83EPpqb4rm6mSiS_-DwoZPD5ug; budibase:init.sig=NdY59ZBecLDWljEoYqtMi8hJlbo; budibase:auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c18xY2MzOWU5ZWE1NDE0ZjM5YTYwZWNjNmUyYmE4MzRmYyIsInNlc3Npb25JZCI6IjMyYTkxNDU0Nzg5MjRiM2Y5MGI3YjY4MDg0ZTVhMzZjIiwidGVuYW50SWQiOiJkZWZhdWx0IiwiaWF0IjoxNjY1MzkyMDIwfQ.bMG8q7WSAqTivEI-PHQgVVYjSdQXMPrHu43ngZ9Hz6Q; budibase:auth.sig=2glQ9XQ8RUC-5Tq4yxrBOa9aVz8; ph_phc_bIjZL7oh2GEUd2vqvTBH8WvrX0fWTFQMs6H5KQxiUxU_posthog=%7B%22distinct_id%22%3A%20%22us_1cc39e9ea5414f39a60ecc6e2ba834fc%22%2C%22%24device_id%22%3A%20%22183b301eb72122f-0a9c4909c701e3-19525635-16a7f0-183b301eb731687%22%2C%22%24user_id%22%3A%20%22us_1cc39e9ea5414f39a60ecc6e2ba834fc%22%2C%22%24initial_referrer%22%3A%20%22https%3A%2F%2Fapps.stegerpfahler.de%2Fbuilder%2Fauth%2Flogin%22%2C%22%24initial_referring_domain%22%3A%20%22apps.stegerpfahler.de%22%2C%22%24active_feature_flags%22%3A%20%5B%5D%7D",
bbapps                |         "if-modified-since": "Fri, 07 Oct 2022 17:23:06 GMT",
bbapps                |         "referer": "https://apps.stegerpfahler.de/builder/portal/apps",
bbapps                |         "sec-fetch-dest": "image",
bbapps                |         "sec-fetch-mode": "no-cors",
bbapps                |         "sec-fetch-site": "same-origin",
bbapps                |         "sec-gpc": "1",
bbapps                |         "x-forwarded-proto": "https"
bbapps                |       },
bbapps                |       "remoteAddress": "::ffff:172.18.0.10",
bbapps                |       "remotePort": 44982
bbapps                |     }
```

**Comment by shogunpurple** [comment]
Hi @davidpfahler - we have a fix for this and it will be rolled out right now. You should still be able to create an app from the "Create app" button and it will work, as a workaround.

**Comment by mike12345567** [comment]
Hi @davidpfahler - if you update your docker-compose installation to 2.0.25 then this problem will be resolved.

**Comment by davidpfahler** [comment]
Thank you for the quick replies!
