### ISSUE TITLE
Unable to progress after Login screen: 'docker-compose up -d' in Google's 'Cloud Shell'

### ISSUE THREAD

**Issue by hAhl2** [Budibase/budibase#8341]
**Hosting**
- Self
  - Method: 'docker-compose up -d' in Google's 'Cloud Shell'
  - Budibase Version: 2.0.33

**Describe the bug**
Unable to progress after Login screen.

**To Reproduce**
Environment: Google's 'Cloud Shell'

following the commands for setting up Budibase via docker-compose, https://docs.budibase.com/docs/docker-compose

Commands:
git clone https://github.com/Budibase/budibase.git
cd budibase/hosting
docker-compose up -d

navigate to port:10000 ( via cloud shell's 'Web Preview')
url generated for preview: https://10000-cs-887327983632-default.cs-us-east1-pkhd.cloudshell.dev/builder/auth/login

do ui stuff: 
create super admin 
login super admin
...'login successful' message
... yet stuck on login page

**Expected behavior**
Progress past the login screen

**Desktop (please complete the following information):**
 - OS: cloud-shell Debian-based Linux operating system
 - Browser: chrome
 - idk version, probably not relevant

**Additional context**
```
docker-compose logs after clicking the 'Sign in to Budibase' button
couchdb-service_1     | 2022-10-20T19:44:42.093620155Z [notice] 2022-10-20T19:44:42.092878Z couchdb@127.0.0.1 <0.2442.0> f9fa25d4f8 couchdb-service:5984 172.21.0.7 budibase GET /global-db/ 200 ok 7
couchdb-service_1     | 2022-10-20T19:44:42.102367679Z [notice] 2022-10-20T19:44:42.101151Z couchdb@127.0.0.1 <0.2443.0> 902a030716 couchdb-service:5984 172.21.0.7 budibase GET /global-db/_design/database/_view/by_email2?include_docs=true&key=%22web.admin%40affectrix.org%22 200 ok 4
bbworker              | 2022-10-20T19:44:42.184931339Z bb-warn: Invalidating sessions for us_43e91f4e8f0c4eafa67dc3f782eafde7 (reason: creation) - us_43e91f4e8f0c4eafa67dc3f782eafde7/7328b170d5f04f13944e5818e2c5ec91
bbproxy               | 2022-10-20T19:44:42.199296110Z 172.21.0.1 - - [20/Oct/2022:19:44:42 +0000] "POST /api/global/auth/default/login HTTP/1.1" 200 2 "https://10000-cs-887327983632-default.cs-us-east1-pkhd.cloudshell.dev/builder/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-" response_time=0.126 proxy_host=worker-service:4003 upstream_addr=172.21.0.7:4003
bbworker              | 2022-10-20T19:44:42.275014072Z ERROR [1666295082273] (29 on 1b51cbaf01b1):
bbworker              | 2022-10-20T19:44:42.275075206Z     req: {
bbworker              | 2022-10-20T19:44:42.275085296Z       "id": 18,
bbworker              | 2022-10-20T19:44:42.275092938Z       "method": "GET",
bbworker              | 2022-10-20T19:44:42.275099443Z       "url": "/api/global/self",
bbworker              | 2022-10-20T19:44:42.275105713Z       "headers": {
bbworker              | 2022-10-20T19:44:42.275112489Z         "host": "127.0.0.1",
bbworker              | 2022-10-20T19:44:42.275119292Z         "connection": "close",
bbworker              | 2022-10-20T19:44:42.275126353Z         "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
bbworker              | 2022-10-20T19:44:42.275133630Z         "accept": "application/json",
bbworker              | 2022-10-20T19:44:42.275140175Z         "accept-encoding": "gzip, deflate, br",
bbworker              | 2022-10-20T19:44:42.275147327Z         "accept-language": "en-US,en;q=0.9",
bbworker              | 2022-10-20T19:44:42.275154921Z         "referer": "https://10000-cs-887327983632-default.cs-us-east1-pkhd.cloudshell.dev/builder/auth/login",
bbworker              | 2022-10-20T19:44:42.275162898Z         "sec-ch-ua": "\"Chromium\";v=\"106\", \"Google Chrome\";v=\"106\", \"Not;A=Brand\";v=\"99\"",
bbworker              | 2022-10-20T19:44:42.275170625Z         "sec-ch-ua-mobile": "?0",
bbworker              | 2022-10-20T19:44:42.275178102Z         "sec-ch-ua-platform": "\"Windows\"",
bbworker              | 2022-10-20T19:44:42.275184301Z         "sec-fetch-dest": "empty",
bbworker              | 2022-10-20T19:44:42.275189921Z         "sec-fetch-mode": "cors",
bbworker              | 2022-10-20T19:44:42.275196452Z         "sec-fetch-site": "same-origin",
bbworker              | 2022-10-20T19:44:42.275202875Z         "x-budibase-api-version": "1",
bbworker              | 2022-10-20T19:44:42.275208920Z         "x-budibase-app-id": ""
bbworker              | 2022-10-20T19:44:42.275215156Z       },
bbworker              | 2022-10-20T19:44:42.275221819Z       "remoteAddress": "::ffff:172.21.0.9",
bbworker              | 2022-10-20T19:44:42.275228285Z       "remotePort": 48398
bbworker              | 2022-10-20T19:44:42.275234887Z     }
bbworker              | 2022-10-20T19:44:42.275242122Z     err: {
bbworker              | 2022-10-20T19:44:42.275248598Z       "type": "ForbiddenError",
bbworker              | 2022-10-20T19:44:42.275255595Z       "message": "Unauthorized - no public worker access",
bbworker              | 2022-10-20T19:44:42.275262756Z       "stack":
bbworker              | 2022-10-20T19:44:42.275269142Z           ForbiddenError: Unauthorized - no public worker access
bbworker              | 2022-10-20T19:44:42.275275566Z               at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
bbworker              | 2022-10-20T19:44:42.275282555Z               at /app/dist/api/index.js:113:18
bbworker              | 2022-10-20T19:44:42.275288830Z               at dispatch (/app/node_modules/koa-compose/index.js:42:32)
bbworker              | 2022-10-20T19:44:42.275295329Z               at /app/node_modules/@koa/router/lib/router.js:368:16
bbworker              | 2022-10-20T19:44:42.275316621Z               at dispatch (/app/node_modules/koa-compose/index.js:42:32)
bbworker              | 2022-10-20T19:44:42.275323144Z               at /app/node_modules/@budibase/pro/dist/index.js:1:34744
bbworker              | 2022-10-20T19:44:42.275329592Z               at Generator.next (<anonymous>)
bbworker              | 2022-10-20T19:44:42.275336204Z               at /app/node_modules/@budibase/pro/dist/index.js:1:832
bbworker              | 2022-10-20T19:44:42.275342487Z               at new Promise (<anonymous>)
bbworker              | 2022-10-20T19:44:42.275349359Z               at __awaiter (/app/node_modules/@budibase/pro/dist/index.js:1:577)
bbworker              | 2022-10-20T19:44:42.275355161Z               at /app/node_modules/@budibase/pro/dist/index.js:1:34392
bbworker              | 2022-10-20T19:44:42.275361302Z               at dispatch (/app/node_modules/koa-compose/index.js:42:32)
bbworker              | 2022-10-20T19:44:42.275369211Z               at /app/node_modules/@koa/router/lib/router.js:368:16
bbworker              | 2022-10-20T19:44:42.275376202Z               at dispatch (/app/node_modules/koa-compose/index.js:42:32)
bbworker              | 2022-10-20T19:44:42.275382727Z               at /app/node_modules/@budibase/backend-core/dist/src/middleware/csrf.js:51:20
bbworker              | 2022-10-20T19:44:42.275389183Z               at Generator.next (<anonymous>)
bbworker              | 2022-10-20T19:44:42.275395621Z       "status": 403,
bbworker              | 2022-10-20T19:44:42.275402221Z       "statusCode": 403,
bbworker              | 2022-10-20T19:44:42.275408565Z       "expose": true
bbworker              | 2022-10-20T19:44:42.275414678Z     }
bbproxy               | 2022-10-20T19:44:42.286542814Z 172.21.0.1 - - [20/Oct/2022:19:44:42 +0000] "GET /api/global/self HTTP/1.1" 403 80 "https://10000-cs-887327983632-default.cs-us-east1-pkhd.cloudshell.dev/builder/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-" response_time=0.014 proxy_host=worker-service:4003 upstream_addr=172.21.0.7:4003
bbproxy               | 2022-10-20T19:44:42.408816336Z 172.21.0.1 - - [20/Oct/2022:19:44:42 +0000] "GET /api/global/configs/checklist?tenantId=default HTTP/1.1" 200 191 "https://10000-cs-887327983632-default.cs-us-east1-pkhd.cloudshell.dev/builder/auth" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-" response_time=0.004 proxy_host=worker-service:4003 upstream_addr=172.21.0.7:4003
bbproxy               | 2022-10-20T19:44:42.481397267Z 172.21.0.1 - - [20/Oct/2022:19:44:42 +0000] "GET /api/system/environment HTTP/1.1" 200 125 "https://10000-cs-887327983632-default.cs-us-east1-pkhd.cloudshell.dev/builder/auth" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-" response_time=0.003 proxy_host=worker-service:4003 upstream_addr=172.21.0.7:4003
couchdb-service_1     | 2022-10-20T19:44:42.577897502Z [notice] 2022-10-20T19:44:42.577394Z couchdb@127.0.0.1 <0.2450.0> 49786a5e53 couchdb-service:5984 172.21.0.7 budibase GET /global-db/ 200 ok 3
couchdb-service_1     | 2022-10-20T19:44:42.587523661Z [notice] 2022-10-20T19:44:42.587129Z couchdb@127.0.0.1 <0.2451.0> 53a6bd6def couchdb-service:5984 172.21.0.7 budibase GET /global-db/_all_docs?include_docs=true&startkey=%22config_settings%22&endkey=%22config_settings%EF%BF%B0%22 200 ok 3
couchdb-service_1     | 2022-10-20T19:44:42.595817762Z [notice] 2022-10-20T19:44:42.595313Z couchdb@127.0.0.1 <0.2452.0> 3c3070bbdc couchdb-service:5984 172.21.0.7 budibase GET /global-db/config_settings? 200 ok 2
couchdb-service_1     | 2022-10-20T19:44:42.605907974Z [notice] 2022-10-20T19:44:42.605042Z couchdb@127.0.0.1 <0.2453.0> 0f5be61f71 couchdb-service:5984 172.21.0.7 budibase GET /global-db/_all_docs?include_docs=true&startkey=%22config_google%22&endkey=%22config_google%EF%BF%B0%22 200 ok 3
couchdb-service_1     | 2022-10-20T19:44:42.613451487Z [notice] 2022-10-20T19:44:42.612940Z couchdb@127.0.0.1 <0.2458.0> 3dd8a9e0f7 couchdb-service:5984 172.21.0.7 budibase GET /global-db/_all_docs?include_docs=true&startkey=%22config_oidc%22&endkey=%22config_oidc%EF%BF%B0%22 200 ok 2
couchdb-service_1     | 2022-10-20T19:44:42.630060765Z [notice] 2022-10-20T19:44:42.626735Z couchdb@127.0.0.1 <0.2459.0> be12b04f56 couchdb-service:5984 172.21.0.7 budibase GET /global-db/_all_docs?include_docs=true&startkey=%22config_settings%22&endkey=%22config_settings%EF%BF%B0%22 200 ok 6
couchdb-service_1     | 2022-10-20T19:44:42.637566967Z [notice] 2022-10-20T19:44:42.636999Z couchdb@127.0.0.1 <0.2460.0> aee2ac398b couchdb-service:5984 172.21.0.7 budibase GET /global-db/config_settings? 200 ok 5
couchdb-service_1     | 2022-10-20T19:44:42.645240402Z [notice] 2022-10-20T19:44:42.644714Z couchdb@127.0.0.1 <0.2461.0> 10e9cb78bf couchdb-service:5984 172.21.0.7 budibase GET /global-db/_all_docs?include_docs=true&startkey=%22config_settings%22&endkey=%22config_settings%EF%BF%B0%22 200 ok 3
couchdb-service_1     | 2022-10-20T19:44:42.652965279Z [notice] 2022-10-20T19:44:42.652461Z couchdb@127.0.0.1 <0.2462.0> 8fc7e5c035 couchdb-service:5984 172.21.0.7 budibase GET /global-db/config_settings? 200 ok 2
bbproxy               | 2022-10-20T19:44:42.656565239Z 172.21.0.1 - - [20/Oct/2022:19:44:42 +0000] "GET /api/global/configs/public?tenantId=default HTTP/1.1" 200 295 "https://10000-cs-887327983632-default.cs-us-east1-pkhd.cloudshell.dev/builder/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-" response_time=0.091 proxy_host=worker-service:4003 upstream_addr=172.21.0.7:4003
couchdb-service_1     | 2022-10-20T19:44:42.741393961Z [notice] 2022-10-20T19:44:42.740813Z couchdb@127.0.0.1 <0.2470.0> 7cadaa8be0 couchdb-service:5984 172.21.0.7 budibase GET /global-db/ 200 ok 2
couchdb-service_1     | 2022-10-20T19:44:42.753156971Z [notice] 2022-10-20T19:44:42.752468Z couchdb@127.0.0.1 <0.2479.0> 27df56b37d couchdb-service:5984 172.21.0.7 budibase GET /global-db/_all_docs?include_docs=true&startkey=%22config_oidc%22&endkey=%22config_oidc%EF%BF%B0%22 200 ok 6
bbproxy               | 2022-10-20T19:44:42.756435088Z 172.21.0.1 - - [20/Oct/2022:19:44:42 +0000] "GET /api/global/configs/public/oidc?tenantId=default HTTP/1.1" 200 2 "https://10000-cs-887327983632-default.cs-us-east1-pkhd.cloudshell.dev/builder/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-" response_time=0.027 proxy_host=worker-service:4003 upstream_addr=172.21.0.7:4003
```

**Comment by jonnymccullagh** [comment]
@hAhl2 After looking into this we think that Google Cloud Shell is interfering with the cookie that BB sets for user login. It would be interesting to know if you have run other apps via docker-compose on Cloud Shell. 
But for now we would recommend you run BB via docker-compose on a virtual machine.   
![image](https://user-images.githubusercontent.com/5209315/197996555-df4ec2a8-a7a1-46a5-b724-ce89f5a32168.png)
