### ISSUE TITLE
ForbiddenError: Unauthorized - no public worker access

### ISSUE THREAD

**Issue by fp57918** [Budibase/budibase#8712]
hi community, we have some weird issue with budibase self hosted running on docker
When we try to create an automation on javascript o bash and we try to write some code we get a toast notification 'error saving automation' randomly but specially when we try to use '' or = or similars.
On bbworker logs we have this lines:

<img width="634" alt="Screenshot 2022-11-17 at 12 24 23" src="https://user-images.githubusercontent.com/97250444/202487410-57cf11f6-9a19-4d63-8c3e-c1fe5a9dd077.png">

` err: {
      "type": "ForbiddenError",
      "message": "Unauthorized - no public worker access",
      "stack":
          ForbiddenError: Unauthorized - no public worker access
              at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
              at /app/dist/api/index.js:117:18
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@koa/router/lib/router.js:368:16
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@budibase/pro/dist/index.js:1:54512
              at Generator.next (<anonymous>)
              at /app/node_modules/@budibase/pro/dist/index.js:1:876
              at new Promise (<anonymous>)
              at __awaiter (/app/node_modules/@budibase/pro/dist/index.js:1:621)
              at /app/node_modules/@budibase/pro/dist/index.js:1:54104
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@koa/router/lib/router.js:368:16
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@budibase/backend-core/dist/src/middleware/csrf.js:51:20
              at Generator.next (<anonymous>)
      "status": 403,
      "statusCode": 403,
      "expose": true
    }`

Walkaround we try : update docker images, rebuild docker , update app to the latest.

Any idea?? thanks !!

**Comment by fp57918** [comment]
The issue was Cloudflare filtering
