### ISSUE TITLE
Getting ERR_SCRIPT_EXECUTION_TIMEOUT while reading single document from MongoDB

### ISSUE THREAD

**Issue by dotrc** [Budibase/budibase#8825]
### Describe the bug
The system works fine when I have less than 100 records in my mongodb collection. But the same screen fails to load with "Bad Request" when I have just about 8500 documents in the mongodb collection. The http://localhost:10000/api/v2/queries/query_datasource_XXX gives a timeout issue in just 1.54 seconds!
`{message: "Bad Request", status: 400, error: {code: "ERR_SCRIPT_EXECUTION_TIMEOUT"}}`

I tried setting the `QUERY_THREAD_TIMEOUT` to `300000` but in vain.

Logs:
```
ERROR [1669452060778] (29 on d372d681ea8d): Bad Request
    BadRequestError: Bad Request
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at /app/dist/api/controllers/query/index.js:247:22
        at Generator.throw (<anonymous>)
        at rejected (/app/dist/api/controllers/query/index.js:6:65)
Trace: BadRequestError: Bad Request
    at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
    at /app/dist/api/controllers/query/index.js:247:22
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/api/controllers/query/index.js:6:65) {
  code: 'ERR_SCRIPT_EXECUTION_TIMEOUT'
}
    at /app/dist/api/index.js:74:21
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/api/index.js:6:65)
INFO  [1669452060781] (29 on d372d681ea8d): request completed
    res: {
      "statusCode": 400,
      "headers": {
        "vary": "Accept-Encoding",
        "content-type": "application/json; charset=utf-8",
        "content-length": "86"
      }
    }
    responseTime: 1505
    req: {
      "id": 146,
      "method": "POST",
      "url": "/api/v2/queries/query_datasource_20d336c7147e422e8def5ca87b3b4438_007bebbca7a6442788b7f7a00994b7c5",
      "headers": {
        "connection": "upgrade",
        "x-real-ip": "172.18.0.1",
        "x-forwarded-for": "172.18.0.1",
        "host": "app-service:4002",
        "content-length": "270",
        "sec-ch-ua": "\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"",
        "x-budibase-app-id": "app_dev_db18d34a46014d41ab406c31f8c3d5ce",
        "x-csrf-token": "3d038c56-6264-47d5-a669-3763ead9ff4a",
        "x-budibase-api-version": "1",
        "sec-ch-ua-mobile": "?0",
        "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
        "content-type": "application/json",
        "accept": "application/json",
        "x-budibase-type": "client",
        "sec-ch-ua-platform": "\"Linux\"",
        "origin": "http://localhost:10000",
        "sec-fetch-site": "same-origin",
        "sec-fetch-mode": "cors",
        "sec-fetch-dest": "empty",
        "referer": "http://localhost:10000/app_dev_db18d34a46014d41ab406c31f8c3d5ce",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.9,de;q=0.8,hi;q=0.7",
        "cookie": "_ga=GA1.1.227352123.1638952864; _pk_id.2.1fff=296f36a7ae55a78b.1653301530.; _ga_FYBCF3Z2W3=GS1.1.1665051369.2.0.1665051369.0.0.0; _pk_ses.2.1fff=1; budibase:auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c18wZWEzNDRhYjYxMDk0ZjQ4YTc2ZjlkODc5YmFlNzlmZiIsInNlc3Npb25JZCI6IjI1NTliMzk4NjNlZjQwNTE4MGI2YTVhNDczYjU1ODc1IiwidGVuYW50SWQiOiJkZWZhdWx0IiwiaWF0IjoxNjY5NDUxOTI4fQ.sSBdG6vnCdWhtCqA-oiQaGsO3889nRsL90PjaTLRZyo; budibase:auth.sig=jc56Hm3_9i5h24O1ip4USUjFgok; ph_phc_bIjZL7oh2GEUd2vqvTBH8WvrX0fWTFQMs6H5KQxiUxU_posthog=%7B%22distinct_id%22%3A%20%22us_0ea344ab61094f48a76f9d879bae79ff%22%2C%22%24device_id%22%3A%20%22183f035743d14f-0c842922b9fc82-11462c6d-1fa400-183f035743e5a8%22%2C%22%24user_id%22%3A%20%22us_0ea344ab61094f48a76f9d879bae79ff%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%2C%22%24active_feature_flags%22%3A%20%5B%5D%7D; budibase:currentapp=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImFwcF9kZXZfZGIxOGQzNGE0NjAxNGQ0MWFiNDA2YzMxZjhjM2Q1Y2UiLCJpYXQiOjE2Njk0NTE5NDZ9.cmXYhFL75yFMDtEPIZQP0Vs5VcEoQJ5MY6Mq60Hp5zQ"
      },
      "remoteAddress": "::ffff:172.18.0.5",
      "remotePort": 49892
    }
```

### System Config:
i7, 16GB
deployment: Self-Hosted using portainer (docker-composed based setup also gave the same issue)

### Mongodb Stat:
```
{
    "ns" : "wniq_nutrition_data.packagedfood",
    "size" : 14634572,
    "count" : 8855,
    "avgObjSize" : 1652,
    "storageSize" : 7708672,
    "freeStorageSize" : 2191360,
    "capped" : false,
    "wiredTiger" : {
        "metadata" : {
            "formatVersion" : 1
        },
        "creationString" : "access_pattern_hint=none,allocation_size=4KB,app_metadata=(formatVersion=1),assert=(commit_timestamp=none,durable_timestamp=none,read_timestamp=none,write_timestamp=off),block_allocation=best,block_compressor=snappy,cache_resident=false,checksum=on,colgroups=,collator=,columns=,dictionary=0,encryption=(keyid=,name=),exclusive=false,extractor=,format=btree,huffman_key=,huffman_value=,ignore_in_memory_cache_size=false,immutable=false,import=(enabled=false,file_metadata=,repair=false),internal_item_max=0,internal_key_max=0,internal_key_truncate=true,internal_page_max=4KB,key_format=q,key_gap=10,leaf_item_max=0,leaf_key_max=0,leaf_page_max=32KB,leaf_value_max=64MB,log=(enabled=true),lsm=(auto_throttle=true,bloom=true,bloom_bit_count=16,bloom_config=,bloom_hash_count=8,bloom_oldest=false,chunk_count_limit=0,chunk_max=5GB,chunk_size=10MB,merge_custom=(prefix=,start_generation=0,suffix=),merge_max=15,merge_min=0),memory_page_image_max=0,memory_page_max=10m,os_cache_dirty_max=0,os_cache_max=0,prefix_compression=false,prefix_compression_min=4,readonly=false,source=,split_deepen_min_child=0,split_deepen_per_child=0,split_pct=90,tiered_object=false,tiered_storage=(auth_token=,bucket=,bucket_prefix=,cache_directory=,local_retention=300,name=,object_target_size=0),type=file,value_format=u,verbose=[],write_timestamp_usage=none",
        "type" : "file",
        "uri" : "statistics:table:collection-2--1615850754350782062",
        "LSM" : {
            "bloom filter false positives" : 0,
            "bloom filter hits" : 0,
            "bloom filter misses" : 0,
            "bloom filter pages evicted from cache" : 0,
            "bloom filter pages read into cache" : 0,
            "bloom filters in the LSM tree" : 0,
            "chunks in the LSM tree" : 0,
            "highest merge generation in the LSM tree" : 0,
            "queries that could have benefited from a Bloom filter that did not exist" : 0,
            "sleep for LSM checkpoint throttle" : 0,
            "sleep for LSM merge throttle" : 0,
            "total size of bloom filters" : 0
        },
        "block-manager" : {
            "allocations requiring file extension" : 0,
            "blocks allocated" : 125,
            "blocks freed" : 74,
            "checkpoint size" : 5500928,
            "file allocation unit size" : 4096,
            "file bytes available for reuse" : 2191360,
            "file magic number" : 120897,
            "file major version number" : 1,
            "file size in bytes" : 7708672,
            "minor version number" : 0
        },
        "btree" : {
            "btree checkpoint generation" : 1810,
            "btree clean tree checkpoint expiration time" : NumberLong(9223372036854775807),
            "btree compact pages reviewed" : 0,
            "btree compact pages selected to be rewritten" : 0,
            "btree compact pages skipped" : 0,
            "btree skipped by compaction as process would not reduce size" : 0,
            "column-store fixed-size leaf pages" : 0,
            "column-store internal pages" : 0,
            "column-store variable-size RLE encoded values" : 0,
            "column-store variable-size deleted values" : 0,
            "column-store variable-size leaf pages" : 0,
            "fixed-record size" : 0,
            "maximum internal page key size" : 368,
            "maximum internal page size" : 4096,
            "maximum leaf page key size" : 2867,
            "maximum leaf page size" : 32768,
            "maximum leaf page value size" : 67108864,
            "maximum tree depth" : 3,
            "number of key/value pairs" : 0,
            "overflow pages" : 0,
            "pages rewritten by compaction" : 0,
            "row-store empty values" : 0,
            "row-store internal pages" : 0,
            "row-store leaf pages" : 0
        },
        "cache" : {
            "bytes currently in the cache" : 16320023,
            "bytes dirty in the cache cumulative" : 8756537,
            "bytes read into cache" : 13898549,
            "bytes written from cache" : 7376975,
            "checkpoint blocked page eviction" : 0,
            "checkpoint of history store file blocked non-history store page eviction" : 0,
            "data source pages selected for eviction unable to be evicted" : 0,
            "eviction gave up due to detecting an out of order on disk value behind the last update on the chain" : 0,
            "eviction gave up due to detecting an out of order tombstone ahead of the selected on disk update" : 0,
            "eviction gave up due to detecting an out of order tombstone ahead of the selected on disk update after validating the update chain" : 0,
            "eviction gave up due to detecting out of order timestamps on the update chain after the selected on disk update" : 0,
            "eviction walk passes of a file" : 0,
            "eviction walk target pages histogram - 0-9" : 0,
            "eviction walk target pages histogram - 10-31" : 0,
            "eviction walk target pages histogram - 128 and higher" : 0,
            "eviction walk target pages histogram - 32-63" : 0,
            "eviction walk target pages histogram - 64-128" : 0,
            "eviction walk target pages reduced due to history store cache pressure" : 0,
            "eviction walks abandoned" : 0,
            "eviction walks gave up because they restarted their walk twice" : 0,
            "eviction walks gave up because they saw too many pages and found no candidates" : 0,
            "eviction walks gave up because they saw too many pages and found too few candidates" : 0,
            "eviction walks reached end of tree" : 0,
            "eviction walks restarted" : 0,
            "eviction walks started from root of tree" : 0,
            "eviction walks started from saved location in tree" : 0,
            "hazard pointer blocked page eviction" : 0,
            "history store table insert calls" : 0,
            "history store table insert calls that returned restart" : 0,
            "history store table out-of-order resolved updates that lose their durable timestamp" : 0,
            "history store table out-of-order updates that were fixed up by reinserting with the fixed timestamp" : 0,
            "history store table reads" : 0,
            "history store table reads missed" : 0,
            "history store table reads requiring squashed modifies" : 0,
            "history store table truncation by rollback to stable to remove an unstable update" : 0,
            "history store table truncation by rollback to stable to remove an update" : 0,
            "history store table truncation to remove an update" : 0,
            "history store table truncation to remove range of updates due to key being removed from the data page during reconciliation" : 0,
            "history store table truncation to remove range of updates due to out-of-order timestamp update on data page" : 0,
            "history store table writes requiring squashed modifies" : 0,
            "in-memory page passed criteria to be split" : 0,
            "in-memory page splits" : 0,
            "internal pages evicted" : 0,
            "internal pages split during eviction" : 0,
            "leaf pages split during eviction" : 0,
            "modified pages evicted" : 0,
            "overflow pages read into cache" : 0,
            "page split during eviction deepened the tree" : 0,
            "page written requiring history store records" : 0,
            "pages read into cache" : 163,
            "pages read into cache after truncate" : 0,
            "pages read into cache after truncate in prepare state" : 0,
            "pages requested from the cache" : 36649,
            "pages seen by eviction walk" : 0,
            "pages written from cache" : 99,
            "pages written requiring in-memory restoration" : 0,
            "the number of times full update inserted to history store" : 0,
            "the number of times reverse modify inserted to history store" : 0,
            "tracked dirty bytes in the cache" : 0,
            "unmodified pages evicted" : 0
        },
        "cache_walk" : {
            "Average difference between current eviction generation when the page was last considered" : 0,
            "Average on-disk page image size seen" : 0,
            "Average time in cache for pages that have been visited by the eviction server" : 0,
            "Average time in cache for pages that have not been visited by the eviction server" : 0,
            "Clean pages currently in cache" : 0,
            "Current eviction generation" : 0,
            "Dirty pages currently in cache" : 0,
            "Entries in the root page" : 0,
            "Internal pages currently in cache" : 0,
            "Leaf pages currently in cache" : 0,
            "Maximum difference between current eviction generation when the page was last considered" : 0,
            "Maximum page size seen" : 0,
            "Minimum on-disk page image size seen" : 0,
            "Number of pages never visited by eviction server" : 0,
            "On-disk page image sizes smaller than a single allocation unit" : 0,
            "Pages created in memory and never written" : 0,
            "Pages currently queued for eviction" : 0,
            "Pages that could not be queued for eviction" : 0,
            "Refs skipped during cache traversal" : 0,
            "Size of the root page" : 0,
            "Total number of pages currently in cache" : 0
        },
        "checkpoint-cleanup" : {
            "pages added for eviction" : 0,
            "pages removed" : 0,
            "pages skipped during tree walk" : 0,
            "pages visited" : 2106
        },
        "compression" : {
            "compressed page maximum internal page size prior to compression" : 4096,
            "compressed page maximum leaf page size prior to compression " : 104864,
            "compressed pages read" : 162,
            "compressed pages written" : 86,
            "page written failed to compress" : 0,
            "page written was too small to compress" : 13
        },
        "cursor" : {
            "Total number of entries skipped by cursor next calls" : 79,
            "Total number of entries skipped by cursor prev calls" : 0,
            "Total number of entries skipped to position the history store cursor" : 0,
            "Total number of times a search near has exited due to prefix config" : 0,
            "bulk loaded cursor insert calls" : 0,
            "cache cursors reuse count" : 3272,
            "close calls that result in cache" : 3272,
            "create calls" : 43,
            "cursor next calls that skip due to a globally visible history store tombstone" : 0,
            "cursor next calls that skip greater than or equal to 100 entries" : 0,
            "cursor next calls that skip less than 100 entries" : 1501594,
            "cursor prev calls that skip due to a globally visible history store tombstone" : 0,
            "cursor prev calls that skip greater than or equal to 100 entries" : 0,
            "cursor prev calls that skip less than 100 entries" : 1,
            "insert calls" : 806,
            "insert key and value bytes" : 1360491,
            "modify" : 604,
            "modify key and value bytes affected" : 1474719,
            "modify value bytes modified" : 13640,
            "next calls" : 1501594,
            "open cursor count" : 0,
            "operation restarted" : 2,
            "prev calls" : 1,
            "remove calls" : 0,
            "remove key bytes removed" : 0,
            "reserve calls" : 0,
            "reset calls" : 9856,
            "search calls" : 24630,
            "search history store calls" : 0,
            "search near calls" : 2226,
            "truncate calls" : 0,
            "update calls" : 0,
            "update key and value bytes" : 0,
            "update value size change" : 0
        },
        "reconciliation" : {
            "approximate byte size of timestamps in pages written" : 0,
            "approximate byte size of transaction IDs in pages written" : 0,
            "dictionary matches" : 0,
            "fast-path pages deleted" : 0,
            "internal page key bytes discarded using suffix compression" : 133,
            "internal page multi-block writes" : 0,
            "internal-page overflow keys" : 0,
            "leaf page key bytes discarded using prefix compression" : 0,
            "leaf page multi-block writes" : 13,
            "leaf-page overflow keys" : 0,
            "maximum blocks required for a page" : 1,
            "overflow values written" : 0,
            "page checksum matches" : 0,
            "page reconciliation calls" : 46,
            "page reconciliation calls for eviction" : 0,
            "pages deleted" : 0,
            "pages written including an aggregated newest start durable timestamp " : 0,
            "pages written including an aggregated newest stop durable timestamp " : 0,
            "pages written including an aggregated newest stop timestamp " : 0,
            "pages written including an aggregated newest stop transaction ID" : 0,
            "pages written including an aggregated newest transaction ID " : 0,
            "pages written including an aggregated oldest start timestamp " : 0,
            "pages written including an aggregated prepare" : 0,
            "pages written including at least one prepare" : 0,
            "pages written including at least one start durable timestamp" : 0,
            "pages written including at least one start timestamp" : 0,
            "pages written including at least one start transaction ID" : 0,
            "pages written including at least one stop durable timestamp" : 0,
            "pages written including at least one stop timestamp" : 0,
            "pages written including at least one stop transaction ID" : 0,
            "records written including a prepare" : 0,
            "records written including a start durable timestamp" : 0,
            "records written including a start timestamp" : 0,
            "records written including a start transaction ID" : 0,
            "records written including a stop durable timestamp" : 0,
            "records written including a stop timestamp" : 0,
            "records written including a stop transaction ID" : 0
        },
        "session" : {
            "object compaction" : 0,
            "tiered operations dequeued and processed" : 0,
            "tiered operations scheduled" : 0,
            "tiered storage local retention time (secs)" : 0
        },
        "transaction" : {
            "race to read prepared update retry" : 0,
            "rollback to stable history store records with stop timestamps older than newer records" : 0,
            "rollback to stable inconsistent checkpoint" : 0,
            "rollback to stable keys removed" : 0,
            "rollback to stable keys restored" : 0,
            "rollback to stable restored tombstones from history store" : 0,
            "rollback to stable restored updates from history store" : 0,
            "rollback to stable skipping delete rle" : 0,
            "rollback to stable skipping stable rle" : 0,
            "rollback to stable sweeping history store keys" : 0,
            "rollback to stable updates removed from history store" : 0,
            "transaction checkpoints due to obsolete pages" : 0,
            "update conflicts" : 0
        }
    },
    "nindexes" : 2,
    "indexBuilds" : [],
    "totalIndexSize" : 385024,
    "totalSize" : 8093696,
    "indexSizes" : {
        "_id_" : 323584,
        "isManual_1_state_1" : 61440
    },
    "scaleFactor" : 1,
    "ok" : 1.0
}
```

**Comment by dotrc** [comment]
We are using find query instead of findOne, as we were not getting the data with findOne, it is giving "No rows found" error. We have got the URL.id binding in place and are passing the id through the URL. When using find (instead of findOne), we are getting the data as expected, but with the issue of timeout.

The findOne query (no field parameters)
![image](https://user-images.githubusercontent.com/878742/204277023-ca8f4bc7-7cba-49cc-aed8-2edc5015d9ae.png)

The data is getting loaded in the designer, but not in the preview of the screen or while in production.

**Comment by melohagan** [comment]
Hmm... I wonder if you tried using the aggregations, rather than transforming the data client side would that help? 

 - https://docs.budibase.com/docs/mongodb#aggregations

**Comment by melohagan** [comment]
Hey @dotrc 

`findOne` should just work:

![Screenshot 2022-11-28 at 14 29 06](https://user-images.githubusercontent.com/101575380/204302750-d1507518-59e2-457d-a889-966ea901772d.png)

![Screenshot 2022-11-28 at 14 29 19](https://user-images.githubusercontent.com/101575380/204302793-50d97d16-7a86-4a59-8d47-b1eb94b88bfb.png)

![Screenshot 2022-11-28 at 14 29 31](https://user-images.githubusercontent.com/101575380/204302847-0654b5e4-f808-48c3-81d1-0a34f816553c.png)

**Comment by melohagan** [comment]
Are you certain the URL id matches a **_id** in one of your MongoDB documents? Bear in mind that if the **_id** field is an object id, then the string value of the URL id will not match.

**Comment by dotrc** [comment]
Yes, I have the Id getting passed to the URL of the target page.
For reading data to populate the form, I don't think we need the name
binding. Will having it cause the problem? Will remove all bindings from
read query and let you know.

**Comment by dotrc** [comment]
Removing the bindings didn't help.
Here's a sample URL: http://localhost:10000/app_dev_67c227c988e34435b21605288734e1da#/my-products/B0BH8KLP96
While I pass the id in the URL, the query does not seem to get it (as seen in the network tool)
![image](https://user-images.githubusercontent.com/878742/204501151-de1871a0-c858-4e5f-902d-f4cb3a5aea53.png)

**Comment by melohagan** [comment]
Could you show me the route you are using for the `my-products` screen please? E.g.
![Screenshot 2022-11-29 at 11 10 33](https://user-images.githubusercontent.com/101575380/204514167-485f0d92-b976-4d6f-aeed-10e12e9a9693.png)

**Comment by dotrc** [comment]
Where do I go from here? Seem to be hitting a stonewall...

**Comment by dotrc** [comment]
Ok, will try doing that.
