### ISSUE TITLE
Error when removing button actions on ejected form block

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#9258]
**Hosting**
- Self
  - Method: Budi CLI
  - Budibase Version: 2.2.9
  - App Version: 2.2.9

**Describe the bug**
When I try to remove button actions from an ejected form-block's save button, I get an error and Budibase becomes unresponsive.

I can recover by refreshing the page

**To Reproduce**
1. Add a form block
2. Eject the block
3. Edit the save button
4. Click define actions
5. Remove an action

Error in console & Budibase crashes:

```
index.db65b971.js:878 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'url')
    at ptt (index.db65b971.js:878:3202)
    at Pe (index.db65b971.js:4:7806)
    at new htt (index.db65b971.js:879:685)
    at VR (index.db65b971.js:886:11258)
    at Object.p (index.db65b971.js:886:11017)
    at Object.p (index.db65b971.js:886:11888)
    at Kn (index.db65b971.js:1:1001844)
    at Object.p (index.db65b971.js:28:45157)
    at bee (index.db65b971.js:4:2737)
    at Ak (index.db65b971.js:4:2404)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium
 - Version: 108.0.5359.124

**Comment by aptkingston** [comment]
I've tried to reproduce this but I can't - did you change any form block settings? If I do those exact steps in cloud (2.2.9) it works fine. I have a feeling I fixed this error already... you're definitely running the latest version?

**Comment by aptkingston** [comment]
Have added a fix to a PR destined for master shortly :+1:
