### ISSUE TITLE
apps-service pod error - bad gateway 502

### ISSUE THREAD

**Issue by driedener** [Budibase/budibase#9298]
**Hosting**

- Self
  - Method: k8s --> AKS with custom ingress
  - Budibase Version: 2.2.9

**Describe the bug**
app-service pods crash after scale out or restart. 

```
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
Error: Name or password is incorrect.
    at responseHandler (/app/node_modules/@budibase/nano/lib/nano.js:193:20)
    at /app/node_modules/@budibase/nano/lib/nano.js:442:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  scope: 'couch',
  statusCode: 401,
  request: {
    method: 'put',
    headers: {
      'content-type': 'application/json',
      accept: 'application/json',
      'user-agent': '@budibase/nano/10.1.1 (Node.js v14.21.2)',
      'Accept-Encoding': 'deflate, gzip',
      Authorization: 'Basic YWRtaW46aWVRNmlUd2txTEpMOU5uc2YyRlU='
    },
    qsStringifyOptions: { arrayFormat: 'repeat' },
    url: 'http://budibase-svc-couchdb:5984/global-db',
    params: undefined,
    paramsSerializer: { serialize: [Function: serialize] },
    data: undefined,
    maxRedirects: 0,
    httpAgent: CookieAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: {},
      freeSockets: [Object],
      keepAliveMsecs: 30000,
      keepAlive: true,
      maxSockets: 50,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      jar: [CookieJar],
      [Symbol(kCapture)]: false,
      [Symbol(cookieOptions)]: undefined
    },
    httpsAgent: CookieAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: {},
      freeSockets: {},
      keepAliveMsecs: 30000,
      keepAlive: true,
      maxSockets: 50,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      jar: [CookieJar],
      [Symbol(kCapture)]: false,
      [Symbol(cookieOptions)]: undefined
    }
  },
  headers: {
    uri: 'http://budibase-svc-couchdb:5984/global-db',
    statusCode: 401,
    'cache-control': 'must-revalidate',
    'content-type': 'application/json',
    date: 'Tue, 10 Jan 2023 15:27:54 GMT',
    'x-couch-request-id': '9eb06cd4ec',
    'x-couchdb-body-time': '0'
  },
  errid: 'non_200',
  description: 'Name or password is incorrect.',
  error: 'unauthorized',
  reason: 'Name or password is incorrect.'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  Error: Name or password is incorrect.
    at responseHandler (/app/node_modules/@budibase/nano/lib/nano.js:193:20)
    at /app/node_modules/@budibase/nano/lib/nano.js:442:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  scope: 'couch',
  statusCode: 401,
  request: {
    method: 'put',
    headers: {
      'content-type': 'application/json',
      accept: 'application/json',
      'user-agent': '@budibase/nano/10.1.1 (Node.js v14.21.2)',
      'Accept-Encoding': 'deflate, gzip',
      Authorization: 'Basic YWRtaW46aWVRNmlUd2txTEpMOU5uc2YyRlU='
    },
    qsStringifyOptions: { arrayFormat: 'repeat' },
    url: 'http://budibase-svc-couchdb:5984/global-db',
    params: undefined,
    paramsSerializer: { serialize: [Function: serialize] },
    data: undefined,
    maxRedirects: 0,
    httpAgent: CookieAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: {},
      freeSockets: [Object],
      keepAliveMsecs: 30000,
      keepAlive: true,
      maxSockets: 50,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      jar: [CookieJar],
      [Symbol(kCapture)]: false,
      [Symbol(cookieOptions)]: undefined
    },
    httpsAgent: CookieAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: {},
      freeSockets: {},
      keepAliveMsecs: 30000,
      keepAlive: true,
      maxSockets: 50,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      jar: [CookieJar],
      [Symbol(kCapture)]: false,
      [Symbol(cookieOptions)]: undefined
    }
  },
  headers: {
    uri: 'http://budibase-svc-couchdb:5984/global-db',
    statusCode: 401,
    'cache-control': 'must-revalidate',
    'content-type': 'application/json',
    date: 'Tue, 10 Jan 2023 15:27:54 GMT',
    'x-couch-request-id': '9eb06cd4ec',
    'x-couchdb-body-time': '0'
  },
  errid: 'non_200',
  description: 'Name or password is incorrect.',
  error: 'unauthorized',
  reason: 'Name or password is incorrect.'
}
lock error
bb-alert: Error performing migrations. Exiting. : {"stack":"Error: Name or password is incorrect.\n    at responseHandler (/app/node_modules/@budibase/nano/lib/nano.js:193:20)\n    at /app/node_modules/@budibase/nano/lib/nano.js:442:13\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","message":"Name or password is incorrect.","scope":"couch","statusCode":401,"request":{"headers":{}},"headers":{"statusCode":401},"errid":"non_200","name":"Error","description":"Name or password is incorrect.","error":"unauthorized","reason":"Name or password is incorrect."}
(node:32) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of undefined
    at shutdown (/app/dist/startup.js:82:12)
    at /app/dist/startup.js:107:17
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/startup.js:29:65)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:32) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
1. create a new budibase deployment as described in: https://docs.budibase.com/docs/kubernetes-k8s
2. delete pod app-service-xxxx and let respawn
3. get pod logs

or

1. create a new budibase deployment as described in: https://docs.budibase.com/docs/kubernetes-k8s
2. scale apps with edited values.yaml
```
  apps:
    port: 4002
    replicaCount: 2
    logLevel: info
    resources: {}

```
4. get pod logs of new pod
5. See error

**Screenshot**
<img width="826" alt="502" src="https://user-images.githubusercontent.com/85668736/211595283-ccb599fb-8935-482e-b4ca-bb25c280251f.png">

**Expected behavior**
Pod should be respawned properly

**Comment by driedener** [comment]
additionally

<img width="1616" alt="pod-events" src="https://user-images.githubusercontent.com/85668736/211606300-be01a901-241b-4d50-96eb-7191044bd8a4.png">

**Comment by driedener** [comment]
just found a workaround/solution: set the secrets of app-service and couchdb manually
uncomment like this in values.yaml and set the secrets

```
  createSecrets: true # creates an internal API key, JWT secrets and redis password for you

  # if createSecrets is set to false, you can hard-code your secrets here
  internalApiKey: "yoursecret"
  jwtSecret: "yoursecret"
  cdnUrl: ""
```
```
couchdb:
  ## clusterSize is the initial size of the CouchDB cluster.
  clusterSize: 3
  allowAdminParty: false

  # Secret Management
  createAdminSecret: true

  adminUsername: budibase
  adminPassword: budibase
  # adminHash: -pbkdf2-this_is_not_necessarily_secure_either
  cookieAuthSecret: admin
```

**Comment by zonywhoop** [comment]
Just upgraded from Budibase helm chart 2.7.x to 2.8.10 and had this same problem.. If the helm chart creates the secrets then on upgrade they appear to change and all access is lost couchdb and the app services no longer function. Defining secrets like this should be better noted in the documentation to enable proper upgrades!
