### ISSUE TITLE
net::ERR_ACCESS_DENIED

### ISSUE THREAD

**Issue by ssshipacarro** [Budibase/budibase#966]
### Error that occurred when using the budibase builder:
```
Error: net::ERR_ACCESS_DENIED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6400)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:482:12)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:137:15)
```
### Operating System Information:
---

Budibase Builder 0.4.3
Electron 10.1.3
darwin 19.6.0
Locale: en-US

**Comment by joebudi** [comment]
Thank you @ssshipacarro . We are looking into this.

**Comment by shogunpurple** [comment]
Has not occurred in quite some time and likely to be resolved with 4001 port fix and updates since. Closing
