### ISSUE TITLE
[BUDI-6598] Automations - looping over create row fails on backend

### ISSUE THREAD

**Issue by oanylund** [Budibase/budibase#9732]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: k8s
  - Budibase Version: 2.3.16 
  - App Version: 2.3.16 

**Describe the bug**
When running a automation with a loop over the "create row" action with array data, the test runner freezes with error:
`TypeError: Cannot read properties of undefined (reading 'filter')`

Looking at the logs of the app-service pod in k8s it looks like this is the actual error:
```
TypeError: Cannot read property 'length' of null
at Object.substituteLoopStep (/app/dist/automations/automationUtils.js:112:32)
    at Orchestrator.<anonymous> (/app/dist/threads/automation.js:289:65)
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/threads/automation.js:28:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at print (/app/node_modules/@budibase/backend-core/dist/src/middleware/logging.js:85:5)
    at console.trace (/app/node_modules/@budibase/backend-core/dist/src/middleware/logging.js:95:33)
    at Object.<anonymous> (/app/dist/automations/utils.js:51:21)
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/automations/utils.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

This happens whatever loop value is set to Array type and value not being an empty array, expect when the array is emtpy.

**To Reproduce**
1. Create a budibase table with one text column id
2. Create a new automation with a cron trigger
3. Add a create row action with the table from step 1 and add looping
4. Set the input type to Array and the binding value to a javascript function `return [{ id: "test" }]`
5. Run the automation from the UI in test
6. See error in console and in app-service

**Expected behavior**
Expected the loop over create row to run one time with `loop.currentItem = { id: "test"}` and create that one row in the table

**Screenshots**
![image](https://user-images.githubusercontent.com/16743890/219865892-35f267d5-d6fc-4b6f-88ff-2a7d25753d20.png)
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

**Additional context**
Switching the create row action with a backend log action everything works as expected.

<sub>[BUDI-6598](https://linear.app/budibase/issue/BUDI-6598/automations-looping-over-create-row-fails-on-backend)</sub>

**Comment by aptkingston** [comment]
Hey @oanylund. I can confirm that this is fixed in our current codebase, and will be included in our next release going out in the next few days.

**Comment by oanylund** [comment]
Awesome! 😄
