### ISSUE TITLE
message :  "Unable to write to object store bucket." status :  500

### ISSUE THREAD

**Issue by aditya-enthu** [Budibase/budibase#9811]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method>  Azure Web App
  - Budibase Version: 2.3.15
  - App Version: <version> 
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**

Deploy Budibase with Azure web app via terrafrom 

```
# Create a new Resource Group
resource "azurerm_resource_group" "main" {
  name     = "${local.aws_tags.Name}-${local.aws_tags.environment}"
  location = var.region
  tags     = local.aws_tags
}

# Create the Linux App Service Plan
resource "azurerm_service_plan" "app_plan" {
  name                = "${local.aws_tags.Name}-app-plan-${local.aws_tags.environment}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  os_type             = "Linux"
  sku_name            = "B2"
  tags                = local.aws_tags
}

# Create the web app, pass in the App Service Plan ID
resource "azurerm_linux_web_app" "webapp" {
  name                = "${local.aws_tags.Name}-webapp-${local.aws_tags.environment}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  service_plan_id     = azurerm_service_plan.app_plan.id
  https_only          = true
  tags                = local.aws_tags

  site_config {
    always_on = true
    application_stack {
      docker_image     = "budibase/budibase-aas"
      docker_image_tag = "v2.3.15"
    }
  }

  logs {
    detailed_error_messages = true
    failed_request_tracing  = true

    http_logs {

      file_system {
        retention_in_days = 1
        retention_in_mb   = 35
      }
    }
  }

  app_settings = {
    "MINIO_ROOT_PASSWORD" = "budibase"
    "MINIO_ROOT_USER"     = "budibase"
  }

  sticky_settings {
    app_setting_names = [
      "APPINSIGHTS_INSTRUMENTATIONKEY",
      "APPLICATIONINSIGHTS_CONNECTION_STRING ",
      "APPINSIGHTS_PROFILERFEATURE_VERSION",
      "APPINSIGHTS_SNAPSHOTFEATURE_VERSION",
      "ApplicationInsightsAgent_EXTENSION_VERSION",
      "XDT_MicrosoftApplicationInsights_BaseExtensions",
      "DiagnosticServices_EXTENSION_VERSION",
      "InstrumentationEngine_EXTENSION_VERSION",
      "SnapshotDebugger_EXTENSION_VERSION",
      "XDT_MicrosoftApplicationInsights_Mode",
      "XDT_MicrosoftApplicationInsights_PreemptSdk",
      "APPLICATIONINSIGHTS_CONFIGURATION_CONTENT",
      "XDT_MicrosoftApplicationInsightsJava",
      "XDT_MicrosoftApplicationInsights_NodeJS",
    ]
  }
}
```

**To Reproduce**
1. Go to '...' Follow instructions to deploy budibase to Azure web app > https://docs.budibase.com/docs/azure-app-service
2. Click on '....' Go to domain created by Azure web app, you are able to login, create user but while creating apps, it errors out.
4. See error >>  {"message":"Unable to write to object store bucket.","status":500}

**Expected behavior**

**Screenshots**
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

```
OS version: Unix 5.4.0.1098
64 bit system: True
64 bit process: True
Processor count: 2
```

**Additional context**

**Comment by OdiJordan** [comment]
Dears, 

I have the same exact error showing up for me when trying to create any app, I have deployed a web app service on Azure, and followed the exact instructions from your documentation but still got the error, all environment variables are created too, it runs for the first time and allows me to create the "Super admin" credentials and then I get "Unable to create object store bucket", is there a solution for this?

Please let me know if you need further logs or screenshots of the issue. 

Much appreciated.
Odi

**Comment by Soumyadip20** [comment]
@aditya-enthu @shogunpurple I am getting the above issue, please help me with the solution?

**Comment by vladaman** [comment]
I am having same issue, clean docker compose install:

```yaml
services:
  budibase:
    restart: unless-stopped
    image: budibase/budibase:latest
      #ports:
      # - 8080:80
    environment:
      JWT_SECRET: pass
      MINIO_ACCESS_KEY: pass
      MINIO_SECRET_KEY: pass
      REDIS_PASSWORD: pass
      COUCHDB_USER: pass
      COUCHDB_PASSWORD: pass
      INTERNAL_API_KEY: pass
    volumes:
      - ./budibase_data:/data

    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.budibase.rule=Host(`ourapps.mydomain.com`)"
      - "traefik.http.routers.budibase.entrypoints=websecure"
      - "traefik.http.routers.budibase.tls=true"
      - "traefik.http.routers.budibase.tls.certresolver=le"

networks:
  web:
    external: true
```

```bash
docker compose up -d
```

Log:
```
udibase-1  | {"level":"ERROR","timestamp":"2025-11-16T07:09:14.415Z","service":"@budibase/server","err":{"type":"Error","message":"Unable to write to object store bucket.","stack":"Error: Unable to write to object store bucket.\n    at createBucketIfNotExists (/backend-core/src/objectStore/objectStore.ts:188:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async initialiseBucket (/backend-core/src/objectStore/objectStore.ts:210:25)\n    at async <anonymous> (/backend-core/src/objectStore/objectStore.ts:385:32)\n    at async Object.streamUploadMany (/backend-core/src/objectStore/objectStore.ts:374:10)\n    at async Promise.all (index 0)\n    at async updateClientLibrary (/app/src/utilities/fileSystem/clientLibrary.ts:125:3)\n    at async uploadAppFiles (/app/src/utilities/fileSystem/app.ts:22:3)\n    at async <anonymous> (/app/src/api/controllers/workspace.ts:479:7)\n    at async performWorkspaceCreate (/app/src/api/controllers/workspace.ts:396:10)\n    at async <anonymous> (/pro/src/sdk/quotas/quotas.ts:126:24)\n    at async <anonymous> (/pro/src/sdk/quotas/quotas.ts:118:7)\n    at async tryIncrement (/pro/src/sdk/quotas/quotas.ts:97:10)\n    at async <anonymous> (/pro/src/sdk/quotas/quotas.ts:82:12)\n    at async increment (/pro/src/sdk/quotas/quotas.ts:80:10)\n    at async create (/app/src/api/controllers/workspace.ts:664:26)\n    at async cleanupMiddleware (/app/src/middleware/cleanup.ts:7:16)\n    at async contentSecurityPolicy (/backend-core/src/middleware/contentSecurityPolicy.ts:134:3)\n    at async /node_modules/koa-compress/lib/index.js:38:5\n    at async <anonymous> (/backend-core/src/middleware/featureFlagCookie.ts:11:5)\n    at async doInFeatureFlagOverrideContext (/backend-core/src/context/mainContext.ts:482:10)\n    at async featureFlagCookie (/backend-core/src/middleware/featureFlagCookie.ts:10:3)"},"pid":320,"tenantId":"default","correlationId":"cc19bec5-fa00-41bb-9f0d-69be7da04572","msg":"Got 400 response code"}
budibase-1  | {"level":"INFO","timestamp":"2025-11-16T07:09:14.423Z","service":"@budibase/server","req":{"method":"POST","url":"/api/applications","correlationId":"cc19bec5-fa00-41bb-9f0d-69be7da04572"},"res":{"status":500},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n    at ServerResponse.D (/node_modules/koa-pino-logger/node_modules/pino-http/logger.js:107:40)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at ServerResponse.emit (/node_modules/dd-trace/packages/datadog-instrumentations/src/http/server.js:46:19)\n    at onFinish (node:_http_outgoing:1081:10)\n    at callback (node:internal/streams/writable:766:21)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)"},"responseTime":699,"msg":"request errored"}
```
